$axure.loadCurrentPage({
  "url":"elb详情.html",
  "generationDate":new Date(1405317786116.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8bde86a4aaf94eafade876b7118c6f30",
    "type":"Axure:Page",
    "name":"ELB详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0ec44e5ff26e4662b056adbab1f100c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":1000,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"233a52263d304c9393ef6af33a0d4ab8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":1000,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/集群详情/u2.png"}},
{
          "id":"0eb8d6b9bb734e47aa682ed6e6bf06ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1000,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"125c65deffc94c8fab00641e60ea8af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1000,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u2.png"}},
{
          "id":"32ba1330bde04b12a7edfeeef94930f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed273df40e114218a809d8f754707cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u4.png"}},
{
          "id":"1bcfeb0ac7274ccb8af792bb6a9699de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":81,
              "y":25},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a56ebba73cb48c9af97502e3d6e14a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":25},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b1755928ba74415926de6c3c05629f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":180,
              "y":26},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f3c29ccd2004e99af58b05687fa8244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":26},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01fd41c4882b4b7fa362e492928a75ad",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"4e0c5c11938a4726ac37eae334aff760",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":251,
              "y":26},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50ae54ba39534bec842c42a676cad425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":251,
                  "y":26},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d8cb938da574beaa002a694ce5c9fb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":295,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"438a5e892b8e4cf79895dbd97b3e8b24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":295,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"4908dbb33182418d808d23a32a29ebb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":295,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"062fe7921591424a862cf63c572b66a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":295,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"4f564ae94e514427a56adaf08d2867c4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"08f8bd6610d6465891bfdc0df3f82f9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":324,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc771406c47e437aa934fe8c2f858afb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35260a55a9424497ab6ca3288a794abd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"13eee6d84dd34803ba0978f1c003dab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":407,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3ac770c29f043578e03800c760ba385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e9ccbb0df0e44e289f320eaaebd5097",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"b8ee1b4618b247f6acf6c9f3c555129e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":487,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d509fb6b92cd4038b2b9b44df86941c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"778482e429a94541b6f7c96df33ac7e6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"15f40ac92c284d78b5454bd25905f316",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":567,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b75c0bcf107b4e72b7effd6fb82eec3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":567,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee16bb7c40bd4874a7b5df7cde59c026",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"2023840017174099ad2fcd11a1d3c41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":647,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"057f251e0dcb455e8ed04100fec9e68c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":647,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25a1c45341334f94b89cea65b7e27ca9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":252,
              "y":64},
            "size":{
              "width":49,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af65c0d046f942cc92d15b9d7202f44e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":252,
                  "y":64},
                "size":{
                  "width":49,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u32.png"}},
{
          "id":"95bdc09c2ef4441584d6d31eb10db712",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":765,
              "y":28},
            "size":{
              "width":139,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"577907ca73d2415aa7c02f6581eaac97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":765,
                  "y":28},
                "size":{
                  "width":139,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66cac5b7bf104313a478c9a91c65f893",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":936,
              "y":27},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d190f622a4496ca789b40b1780a4a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":27},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"013433abe33246dc845ab6817446253f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":381,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9c2911aa3234090a97d9dc407ac708f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":381,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"ac1a2abf197d41cd9957376f095232d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":381,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a037cbe24447c49078464999ba4489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":381,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"9e84102959034e938242c1b6c35812f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":913,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f69addcf9cef41158375cb80ddcdfed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":913,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"3c64975d7f2540ed9a1806c4411cbaff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":913,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"713e632f0cad406ba325acd226a199f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":913,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"e2691e1f651341c993961334b4e9fc11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":964,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d95b4fc1171948d189749b58f06f8b88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":964,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"48c2329e36a4451ca78beec972a4e7dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":964,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e9389cdefd74fa1a80a1beb7f163ba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":964,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"6ab60504c55941d9a659a8d40f980500",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "location":{
              "x":903,
              "y":13},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75504288ac14a34ab250a98d2e1a0ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "location":{
                  "x":903,
                  "y":13},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u100.png"}},
{
          "id":"79292251e9324a19a6e9831d2ddf091b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":30,
              "y":91},
            "size":{
              "width":443,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517f0104a831403ea154ee22e2dc3327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":30,
                  "y":91},
                "size":{
                  "width":443,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a42624917af44d58ae4ae185b62a232d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":28,
              "y":121},
            "size":{
              "width":40,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c24f4ba4d7247abaec21984f5ab869e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":28,
                  "y":121},
                "size":{
                  "width":40,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u77.png"}},
{
          "id":"f0c5a5221e1146f0bcf9630f1427ec06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":69,
              "y":133},
            "size":{
              "width":200,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e003fab39df94939b9286ce138b27285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":69,
                  "y":133},
                "size":{
                  "width":200,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12bd7c3909b54c889ca2544f8d4d1ade",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":30,
              "y":239},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce22e2a5cd5c4938901a256c71cbefac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":30,
                  "y":239},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20755dc4493f47a68725b5d80f59aea5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":30,
              "y":259},
            "size":{
              "width":76,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d59d097894c4a48bfcc2401d1a19c69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":30,
                  "y":259},
                "size":{
                  "width":76,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u85.png"}},
{
          "id":"dedd202390dd44ce8f3776787f0735bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":149,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aebe4c90665743da802a53f3a37076e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":149,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u88.png"}},
{
          "id":"4474a95f2c3b4ed3bc8bb2c2ef4a54bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":268,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f225e2d778ec41bf8425e2ba1438abc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":268,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u88.png"}},
{
          "id":"d2ad255b4621419bb8392badf2fc1b40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":30,
              "y":272},
            "size":{
              "width":460,
              "height":115},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91bbf893c63f4c6eb59604fa9048fd91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":30,
                  "y":272},
                "size":{
                  "width":460,
                  "height":115},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情_1/u79.png"}},
{
          "id":"81a40de83a3a486482d09643a912ca2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":51,
              "y":292},
            "size":{
              "width":145,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f52f7d74b4a4749accf250974b03702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":51,
                  "y":292},
                "size":{
                  "width":145,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"daaf2bb291f84a38aa996ea6ace11579",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":265,
              "y":292},
            "size":{
              "width":91,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aec4b493f2a4d40888317630108774a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":265,
                  "y":292},
                "size":{
                  "width":91,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e22a61d882a8427c816bd9588173237b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":51,
              "y":324},
            "size":{
              "width":61,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87d2a59d494243f590fd147fd9a0d952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":51,
                  "y":324},
                "size":{
                  "width":61,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"849fa6f50381415993120f00a03627d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":265,
              "y":353},
            "size":{
              "width":61,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2799047cb0b416885224441abb1ada9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":353},
                "size":{
                  "width":61,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4419f689d8aa422382c444770de7d13b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":325,
              "y":353},
            "size":{
              "width":115,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94cce37aafa446d5b13732815ae6bbc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":325,
                  "y":353},
                "size":{
                  "width":115,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddfa90e03eee478da253e370460a8df5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":373,
              "y":291},
            "size":{
              "width":13,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59bb9f3c541f43f78c58afd7aa0dbf5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":373,
                  "y":291},
                "size":{
                  "width":13,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例/u392.png"}},
{
          "id":"3d70d6f09f8142f1a285e86eaedcf0d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":511,
              "y":238},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"049cdc548d224328b2cbae204b59b2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":511,
                  "y":238},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0003f964095f45939210c65734fc7c60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":511,
              "y":258},
            "size":{
              "width":95,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e30294aefe642b18df590cbac0bf492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":511,
                  "y":258},
                "size":{
                  "width":95,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情_1/u77.png"}},
{
          "id":"6d46db194f074d08822a03cc563b04fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":511,
              "y":271},
            "size":{
              "width":460,
              "height":116},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af780dd1e530432c8d5d98ffabc08a4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":511,
                  "y":271},
                "size":{
                  "width":460,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elb详情/u84.png"}},
{
          "id":"52c0852ae59442718593f6ea1b1db167",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":531,
              "y":291},
            "size":{
              "width":61,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef3f7f2d1cfc477791284ee3be130bb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":531,
                  "y":291},
                "size":{
                  "width":61,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d7d5f000c1d470c9b88769a2aa517c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF26CE00},
            "location":{
              "x":592,
              "y":292},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF26CE00},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950cc57a1aaf4aec92986a4de2bc9827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF26CE00},
                "location":{
                  "x":592,
                  "y":292},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF26CE00},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u117.png"}},
{
          "id":"d7700bf44ba44e81b5f4950482b44bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF26CE00,
              "opacity":1},
            "location":{
              "x":608,
              "y":291},
            "size":{
              "width":163,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37f074e9a8bd45069a62683f5c21f32c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF26CE00,
                  "opacity":1},
                "location":{
                  "x":608,
                  "y":291},
                "size":{
                  "width":163,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae9a19f3b035402ab68b99dad2aa3deb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":744,
              "y":290},
            "size":{
              "width":121,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba042ee53c4a4cceb7ae23f20c9335c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":744,
                  "y":290},
                "size":{
                  "width":121,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7d0a8587aeb49c8823e39e1527ea0fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":265,
              "y":324},
            "size":{
              "width":79,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"331ff30c0ec34dbcbff833f284de64b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":265,
                  "y":324},
                "size":{
                  "width":79,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e8f8f6db4d7461b856159591f899391",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":531,
              "y":324},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9e5eb5e3aee4096a1148dac507f3ddd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":531,
                  "y":324},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82341e02914845cf849bf904acd38d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":387,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f323a6e8679f4bde822b343f7a7428d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":387,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u88.png"}},
{
          "id":"c70671deb1c1424299c9609493e27e7c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":218},
            "size":{
              "width":840,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/集群详情/u110_line.png"}},
{
          "id":"9e8f147ef0f64b949d0addcd354540fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":30,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8587fefd3b89413787234bf2d1b9ff7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":30,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u81.png"}},
{
          "id":"dbdd88e2d6c2411697ef923134efb7b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":51,
              "y":353},
            "size":{
              "width":49,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6077928bafc540189cf77dd5d5234bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":353},
                "size":{
                  "width":49,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b56d31d957d54e4393b560609b379a89",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":99,
              "y":353},
            "size":{
              "width":79,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e86f54b49d84ad7a1cee5876fd89a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":99,
                  "y":353},
                "size":{
                  "width":79,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e2b345f903343e0be8a7b5112707589",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":256},
            "size":{
              "width":384,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/elb详情/u107_line.png"}},
{
          "id":"6e09c19a9b874fad806675127c2e0002",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":255},
            "size":{
              "width":366,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/elb详情/u108_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0ec44e5ff26e4662b056adbab1f100c8":{
      "scriptId":"u0"},
    "233a52263d304c9393ef6af33a0d4ab8":{
      "scriptId":"u1"},
    "0eb8d6b9bb734e47aa682ed6e6bf06ae":{
      "scriptId":"u2"},
    "125c65deffc94c8fab00641e60ea8af6":{
      "scriptId":"u3"},
    "32ba1330bde04b12a7edfeeef94930f8":{
      "scriptId":"u4"},
    "ed273df40e114218a809d8f754707cec":{
      "scriptId":"u5"},
    "1bcfeb0ac7274ccb8af792bb6a9699de":{
      "scriptId":"u6"},
    "7a56ebba73cb48c9af97502e3d6e14a4":{
      "scriptId":"u7"},
    "0b1755928ba74415926de6c3c05629f1":{
      "scriptId":"u8"},
    "4f3c29ccd2004e99af58b05687fa8244":{
      "scriptId":"u9"},
    "01fd41c4882b4b7fa362e492928a75ad":{
      "scriptId":"u10"},
    "4e0c5c11938a4726ac37eae334aff760":{
      "scriptId":"u11"},
    "50ae54ba39534bec842c42a676cad425":{
      "scriptId":"u12"},
    "0d8cb938da574beaa002a694ce5c9fb1":{
      "scriptId":"u13"},
    "438a5e892b8e4cf79895dbd97b3e8b24":{
      "scriptId":"u14"},
    "4908dbb33182418d808d23a32a29ebb6":{
      "scriptId":"u15"},
    "062fe7921591424a862cf63c572b66a3":{
      "scriptId":"u16"},
    "4f564ae94e514427a56adaf08d2867c4":{
      "scriptId":"u17"},
    "08f8bd6610d6465891bfdc0df3f82f9e":{
      "scriptId":"u18"},
    "dc771406c47e437aa934fe8c2f858afb":{
      "scriptId":"u19"},
    "35260a55a9424497ab6ca3288a794abd":{
      "scriptId":"u20"},
    "13eee6d84dd34803ba0978f1c003dab0":{
      "scriptId":"u21"},
    "c3ac770c29f043578e03800c760ba385":{
      "scriptId":"u22"},
    "0e9ccbb0df0e44e289f320eaaebd5097":{
      "scriptId":"u23"},
    "b8ee1b4618b247f6acf6c9f3c555129e":{
      "scriptId":"u24"},
    "d509fb6b92cd4038b2b9b44df86941c7":{
      "scriptId":"u25"},
    "778482e429a94541b6f7c96df33ac7e6":{
      "scriptId":"u26"},
    "15f40ac92c284d78b5454bd25905f316":{
      "scriptId":"u27"},
    "b75c0bcf107b4e72b7effd6fb82eec3d":{
      "scriptId":"u28"},
    "ee16bb7c40bd4874a7b5df7cde59c026":{
      "scriptId":"u29"},
    "2023840017174099ad2fcd11a1d3c41d":{
      "scriptId":"u30"},
    "057f251e0dcb455e8ed04100fec9e68c":{
      "scriptId":"u31"},
    "25a1c45341334f94b89cea65b7e27ca9":{
      "scriptId":"u32"},
    "af65c0d046f942cc92d15b9d7202f44e":{
      "scriptId":"u33"},
    "95bdc09c2ef4441584d6d31eb10db712":{
      "scriptId":"u34"},
    "577907ca73d2415aa7c02f6581eaac97":{
      "scriptId":"u35"},
    "66cac5b7bf104313a478c9a91c65f893":{
      "scriptId":"u36"},
    "e8d190f622a4496ca789b40b1780a4a6":{
      "scriptId":"u37"},
    "013433abe33246dc845ab6817446253f":{
      "scriptId":"u38"},
    "b9c2911aa3234090a97d9dc407ac708f":{
      "scriptId":"u39"},
    "ac1a2abf197d41cd9957376f095232d0":{
      "scriptId":"u40"},
    "14a037cbe24447c49078464999ba4489":{
      "scriptId":"u41"},
    "9e84102959034e938242c1b6c35812f7":{
      "scriptId":"u42"},
    "f69addcf9cef41158375cb80ddcdfed3":{
      "scriptId":"u43"},
    "3c64975d7f2540ed9a1806c4411cbaff":{
      "scriptId":"u44"},
    "713e632f0cad406ba325acd226a199f6":{
      "scriptId":"u45"},
    "e2691e1f651341c993961334b4e9fc11":{
      "scriptId":"u46"},
    "d95b4fc1171948d189749b58f06f8b88":{
      "scriptId":"u47"},
    "48c2329e36a4451ca78beec972a4e7dd":{
      "scriptId":"u48"},
    "9e9389cdefd74fa1a80a1beb7f163ba3":{
      "scriptId":"u49"},
    "6ab60504c55941d9a659a8d40f980500":{
      "scriptId":"u50"},
    "a75504288ac14a34ab250a98d2e1a0ba":{
      "scriptId":"u51"},
    "79292251e9324a19a6e9831d2ddf091b":{
      "scriptId":"u52"},
    "517f0104a831403ea154ee22e2dc3327":{
      "scriptId":"u53"},
    "a42624917af44d58ae4ae185b62a232d":{
      "scriptId":"u54"},
    "7c24f4ba4d7247abaec21984f5ab869e":{
      "scriptId":"u55"},
    "f0c5a5221e1146f0bcf9630f1427ec06":{
      "scriptId":"u56"},
    "e003fab39df94939b9286ce138b27285":{
      "scriptId":"u57"},
    "12bd7c3909b54c889ca2544f8d4d1ade":{
      "scriptId":"u58"},
    "ce22e2a5cd5c4938901a256c71cbefac":{
      "scriptId":"u59"},
    "20755dc4493f47a68725b5d80f59aea5":{
      "scriptId":"u60"},
    "5d59d097894c4a48bfcc2401d1a19c69":{
      "scriptId":"u61"},
    "dedd202390dd44ce8f3776787f0735bf":{
      "scriptId":"u62"},
    "aebe4c90665743da802a53f3a37076e9":{
      "scriptId":"u63"},
    "4474a95f2c3b4ed3bc8bb2c2ef4a54bb":{
      "scriptId":"u64"},
    "f225e2d778ec41bf8425e2ba1438abc0":{
      "scriptId":"u65"},
    "d2ad255b4621419bb8392badf2fc1b40":{
      "scriptId":"u66"},
    "91bbf893c63f4c6eb59604fa9048fd91":{
      "scriptId":"u67"},
    "81a40de83a3a486482d09643a912ca2b":{
      "scriptId":"u68"},
    "6f52f7d74b4a4749accf250974b03702":{
      "scriptId":"u69"},
    "daaf2bb291f84a38aa996ea6ace11579":{
      "scriptId":"u70"},
    "2aec4b493f2a4d40888317630108774a":{
      "scriptId":"u71"},
    "e22a61d882a8427c816bd9588173237b":{
      "scriptId":"u72"},
    "87d2a59d494243f590fd147fd9a0d952":{
      "scriptId":"u73"},
    "849fa6f50381415993120f00a03627d9":{
      "scriptId":"u74"},
    "f2799047cb0b416885224441abb1ada9":{
      "scriptId":"u75"},
    "4419f689d8aa422382c444770de7d13b":{
      "scriptId":"u76"},
    "94cce37aafa446d5b13732815ae6bbc9":{
      "scriptId":"u77"},
    "ddfa90e03eee478da253e370460a8df5":{
      "scriptId":"u78"},
    "59bb9f3c541f43f78c58afd7aa0dbf5a":{
      "scriptId":"u79"},
    "3d70d6f09f8142f1a285e86eaedcf0d1":{
      "scriptId":"u80"},
    "049cdc548d224328b2cbae204b59b2dd":{
      "scriptId":"u81"},
    "0003f964095f45939210c65734fc7c60":{
      "scriptId":"u82"},
    "5e30294aefe642b18df590cbac0bf492":{
      "scriptId":"u83"},
    "6d46db194f074d08822a03cc563b04fa":{
      "scriptId":"u84"},
    "af780dd1e530432c8d5d98ffabc08a4e":{
      "scriptId":"u85"},
    "52c0852ae59442718593f6ea1b1db167":{
      "scriptId":"u86"},
    "ef3f7f2d1cfc477791284ee3be130bb5":{
      "scriptId":"u87"},
    "5d7d5f000c1d470c9b88769a2aa517c1":{
      "scriptId":"u88"},
    "950cc57a1aaf4aec92986a4de2bc9827":{
      "scriptId":"u89"},
    "d7700bf44ba44e81b5f4950482b44bf6":{
      "scriptId":"u90"},
    "37f074e9a8bd45069a62683f5c21f32c":{
      "scriptId":"u91"},
    "ae9a19f3b035402ab68b99dad2aa3deb":{
      "scriptId":"u92"},
    "ba042ee53c4a4cceb7ae23f20c9335c7":{
      "scriptId":"u93"},
    "c7d0a8587aeb49c8823e39e1527ea0fb":{
      "scriptId":"u94"},
    "331ff30c0ec34dbcbff833f284de64b1":{
      "scriptId":"u95"},
    "0e8f8f6db4d7461b856159591f899391":{
      "scriptId":"u96"},
    "c9e5eb5e3aee4096a1148dac507f3ddd":{
      "scriptId":"u97"},
    "82341e02914845cf849bf904acd38d05":{
      "scriptId":"u98"},
    "f323a6e8679f4bde822b343f7a7428d0":{
      "scriptId":"u99"},
    "c70671deb1c1424299c9609493e27e7c":{
      "scriptId":"u100"},
    "9e8f147ef0f64b949d0addcd354540fa":{
      "scriptId":"u101"},
    "8587fefd3b89413787234bf2d1b9ff7d":{
      "scriptId":"u102"},
    "dbdd88e2d6c2411697ef923134efb7b0":{
      "scriptId":"u103"},
    "6077928bafc540189cf77dd5d5234bb0":{
      "scriptId":"u104"},
    "b56d31d957d54e4393b560609b379a89":{
      "scriptId":"u105"},
    "7e86f54b49d84ad7a1cee5876fd89a73":{
      "scriptId":"u106"},
    "2e2b345f903343e0be8a7b5112707589":{
      "scriptId":"u107"},
    "6e09c19a9b874fad806675127c2e0002":{
      "scriptId":"u108"}}});