$axure.loadCurrentPage({
  "url":"我的服务.html",
  "generationDate":new Date(1405317800566.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e8202ff5c14048f7acf523f53abb0635",
    "type":"Axure:Page",
    "name":"我的服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7bc3975fc7e24a38841eebc633cbe560",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":1000,
              "height":730},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac9f8cd3771b40238c7f4e5abb418dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":1000,
                  "height":730},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息/u0.png"}},
{
          "id":"bc9f5b8cf5a94de49c7f4d08f1e56120",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1000,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75c87ca0db5d46d6a36769ec73b349a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1000,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u2.png"}},
{
          "id":"ffdd11d72b2447eaa885b94ace56a8f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f31f9f87ecc94a028a8b929c1453fc9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u4.png"}},
{
          "id":"d151a4ed730046f2bd1c06b362f28104",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":81,
              "y":25},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a2a6790d41a4ded88365e200d0409e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":25},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5c220c84c704d75b14cf70ff04dc854",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":180,
              "y":26},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c72e4c2ebba44158e7b2d1a65885ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":26},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54ecf4a1494a4ed4ba9d904f036966a5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"7a60e238fcb0466ba0cbf2702d496237",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":251,
              "y":26},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"145db6a8b34d4f0b873711e83260248e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":251,
                  "y":26},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ba338178d2c4ebab943376aec7b701e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":295,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff237a766c404eef8a7bc8cf00725bf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":295,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"00db78a84364401e80c5246d082d62d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":295,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2986d6292a384bcc9c52032650def029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":295,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"9cc2d22ff3ea458e9d967d890ae59219",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"413bf349534048f4b0b30712516e2aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":324,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78595d4529114575b90ee8b9f8c31cfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"878e40fb47c241b0850c153c649a44e3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"95421cae18df4f56a1aa29d542b7983a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":407,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fad27fa6749848e3b7cd19fb6216b555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"530e35c6bcd9426782c7ac0d99e78a72",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"6f305748671847a38d7c7d907ff3ccd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":487,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de22a6c60f9549718d8e3446f1a52926",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"396ea49e8ef54d68a747cf00ac38393e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"fd70301510984ebaaff8fde085eddbc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":567,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff403ae46074053b1a0bd6f46809782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":567,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e2e92b9b5b24b4c989513bb1d333fd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":566,
              "y":64},
            "size":{
              "width":58,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"192f7fbbbb18491f824c61c512287d93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":566,
                  "y":64},
                "size":{
                  "width":58,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u29.png"}},
{
          "id":"879a797992694ea093fbd00ec1d54c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":765,
              "y":28},
            "size":{
              "width":139,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8ad6c14c1864f44ae6809c571a75c48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":765,
                  "y":28},
                "size":{
                  "width":139,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35a59415a44b4d6b9519834d861235f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":936,
              "y":27},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e72c31218e884eeb80ba027768da6dd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":27},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2aba03944b99410c92a0daeae3b47559",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":381,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f7119b298c490aabbcf576b8322d3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":381,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"84293d3787304c519838c0acde978d24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":381,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa453dce3c444f9eb0d271fa617f3685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":381,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"065b261cdad34f829cfa7364f5b84776",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":913,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"539237c79bc24168b7c9a7c04b943318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":913,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"99b331cba1784a37b64cdfdc9f28916d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":913,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"377ce0b8ec9642a4816840218656ba47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":913,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"6a931e74daf34a28a2e60280bd97ff9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":964,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"642fad26a8cd4afc942385576d640a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":964,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"cb9ae1aec29c496a99a82bb334f9d551",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":964,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3257cda772084b8dbc1499c679ed78f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":964,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"766a42a927e04ad59242adece750b330",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":200,
              "height":730},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00fedd38ae4041cd86a30560c29bdf20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":200,
                  "height":730},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息/u50.png"}},
{
          "id":"c30daff18889494cb0c0da7573608488",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":31,
              "y":149},
            "size":{
              "width":29,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d598534d4bd640ddb46a08e4238fbb7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":31,
                  "y":149},
                "size":{
                  "width":29,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u52.png"}},
{
          "id":"8c96335858174bdea405fb91959e2c64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF32445B,
              "opacity":1},
            "location":{
              "x":70,
              "y":157},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3742f54533340b8b563a7f51982cdd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF32445B,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":157},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5283933c9bcf4b48bab36301fe0fffd1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":185},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u56_line.png"}},
{
          "id":"1fd39f2018994e0e9f4657a81a8c3171",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":93},
            "size":{
              "width":113,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dad931d31de94640a311aed5386c8c77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":93},
                "size":{
                  "width":113,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d5bee13236c43d68223ea6380628e96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "location":{
              "x":903,
              "y":13},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f06ddb9196948e887cc81140cce65c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "location":{
                  "x":903,
                  "y":13},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u100.png"}},
{
          "id":"c7fb945d650e4deb9e3c70bf17d372ec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":125},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u56_line.png"}},
{
          "id":"897686583e4145c7b97c1467302a42be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF32445B,
              "opacity":1},
            "location":{
              "x":33,
              "y":92},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd0d47b990344048f3b652429a494fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF32445B,
                  "opacity":1},
                "location":{
                  "x":33,
                  "y":92},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83e06133518d40e48f5c8b2f79ecaf0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":185,
              "y":149},
            "size":{
              "width":36,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f89fdefaaf7445d7940960394c247dfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":185,
                  "y":149},
                "size":{
                  "width":36,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u214.png"}},
{
          "id":"c328d660f7d24a8bafd9b8c171d132ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":200,
              "y":145},
            "size":{
              "width":23,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f48d2ef9ec124e9b82218ac03f2f71cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":200,
                  "y":145},
                "size":{
                  "width":23,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u216.png"}},
{
          "id":"67511cc2cf6f47d198f3aa61cb2e3e5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFDCE4EA},
            "location":{
              "x":194,
              "y":161},
            "size":{
              "width":6,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5261e700066d4a07b3706ebd637ff290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA},
                "location":{
                  "x":194,
                  "y":161},
                "size":{
                  "width":6,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u218.png"}},
{
          "id":"da8f9e085fea4731913470e2ea48eb9c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"2c040a183027416db62246032503a7e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":241,
              "y":142},
            "size":{
              "width":161,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d3756173d914c90981f745939954da9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":241,
                  "y":142},
                "size":{
                  "width":161,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80fb0c5b8d1e43118fdcad6f06aa222f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":465,
              "y":142},
            "size":{
              "width":161,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c371cfe91e48c6975cc611df9c65f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":142},
                "size":{
                  "width":161,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ade55c0fcec42f0b95f06fb0e1d8d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":756,
              "y":142},
            "size":{
              "width":85,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272e12a6f43d46ffa3c486c3c8d816a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":756,
                  "y":142},
                "size":{
                  "width":85,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"901eb6caf0674de78ed97ff6d54190f2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":131},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u289_line.png"}},
{
          "id":"4bfb410bd95c4ae9ae9cebad4fee7672",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":131},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u289_line.png"}},
{
          "id":"b03855078dfe47ec8ec5a956caafe1cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":241,
              "y":181},
            "size":{
              "width":161,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ca5625a6ce4acc959079e46c8d4135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":241,
                  "y":181},
                "size":{
                  "width":161,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84f976456c9c4a3d85f0e990366dfb70",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":464,
              "y":181},
            "size":{
              "width":176,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e7df0a24564bd3a335eab1122feb1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":464,
                  "y":181},
                "size":{
                  "width":176,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e56aa12a790543adb16efa40315e12da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":756,
              "y":181},
            "size":{
              "width":104,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12bb0f3bd19e4a4a91e15163ac35c601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":756,
                  "y":181},
                "size":{
                  "width":104,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14fe4fa4408c47f5b45bcd7f519c8cb6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":160},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"e3f17da4725a4eb3a37dafac9b851384",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":202},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"481bdc13df49444595c5c7bd06b85b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":241,
              "y":223},
            "size":{
              "width":161,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28922d4227ae413286edc4eb88ae726f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":241,
                  "y":223},
                "size":{
                  "width":161,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5455110d02494edda47bb840441eedf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":464,
              "y":223},
            "size":{
              "width":91,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c1a6af7dd2946299e101d60fb791aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":464,
                  "y":223},
                "size":{
                  "width":91,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7af961a1a3794542bdf8f82697ff2840",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":756,
              "y":223},
            "size":{
              "width":104,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7151a9040b4e9c9aaaa5208b14a37e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":756,
                  "y":223},
                "size":{
                  "width":104,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0dd40dc2d454a9384c2a82c7f09b5b9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":202},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"61090560e5f44e88be5c90c44637d8f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":244},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"ee1553f6f5b849dda2497cf4f9598c19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":622,
              "y":181},
            "size":{
              "width":104,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d82da34f5a7486facd8c09316cccbdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":622,
                  "y":181},
                "size":{
                  "width":104,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e558a74f146476d9ff993e2b0eeff37",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":267},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92542a9136e446128a58fb8ed81bb5ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":267},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bc5571a94f104dd68b7984cece45eae8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":251,
              "y":269},
            "size":{
              "width":199,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"966f6bd3aaad49829f9e520458790f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":251,
                  "y":269},
                "size":{
                  "width":199,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9da275aa29064b418548e4e6dfb7c59d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":230,
              "y":300},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7f61435eed8414b93966fca6fd8140b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":230,
                  "y":300},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u291.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7bc3975fc7e24a38841eebc633cbe560":{
      "scriptId":"u0"},
    "ac9f8cd3771b40238c7f4e5abb418dc3":{
      "scriptId":"u1"},
    "bc9f5b8cf5a94de49c7f4d08f1e56120":{
      "scriptId":"u2"},
    "75c87ca0db5d46d6a36769ec73b349a1":{
      "scriptId":"u3"},
    "ffdd11d72b2447eaa885b94ace56a8f7":{
      "scriptId":"u4"},
    "f31f9f87ecc94a028a8b929c1453fc9f":{
      "scriptId":"u5"},
    "d151a4ed730046f2bd1c06b362f28104":{
      "scriptId":"u6"},
    "7a2a6790d41a4ded88365e200d0409e8":{
      "scriptId":"u7"},
    "f5c220c84c704d75b14cf70ff04dc854":{
      "scriptId":"u8"},
    "9c72e4c2ebba44158e7b2d1a65885ae1":{
      "scriptId":"u9"},
    "54ecf4a1494a4ed4ba9d904f036966a5":{
      "scriptId":"u10"},
    "7a60e238fcb0466ba0cbf2702d496237":{
      "scriptId":"u11"},
    "145db6a8b34d4f0b873711e83260248e":{
      "scriptId":"u12"},
    "2ba338178d2c4ebab943376aec7b701e":{
      "scriptId":"u13"},
    "ff237a766c404eef8a7bc8cf00725bf7":{
      "scriptId":"u14"},
    "00db78a84364401e80c5246d082d62d2":{
      "scriptId":"u15"},
    "2986d6292a384bcc9c52032650def029":{
      "scriptId":"u16"},
    "9cc2d22ff3ea458e9d967d890ae59219":{
      "scriptId":"u17"},
    "413bf349534048f4b0b30712516e2aa1":{
      "scriptId":"u18"},
    "78595d4529114575b90ee8b9f8c31cfc":{
      "scriptId":"u19"},
    "878e40fb47c241b0850c153c649a44e3":{
      "scriptId":"u20"},
    "95421cae18df4f56a1aa29d542b7983a":{
      "scriptId":"u21"},
    "fad27fa6749848e3b7cd19fb6216b555":{
      "scriptId":"u22"},
    "530e35c6bcd9426782c7ac0d99e78a72":{
      "scriptId":"u23"},
    "6f305748671847a38d7c7d907ff3ccd3":{
      "scriptId":"u24"},
    "de22a6c60f9549718d8e3446f1a52926":{
      "scriptId":"u25"},
    "396ea49e8ef54d68a747cf00ac38393e":{
      "scriptId":"u26"},
    "fd70301510984ebaaff8fde085eddbc7":{
      "scriptId":"u27"},
    "7ff403ae46074053b1a0bd6f46809782":{
      "scriptId":"u28"},
    "0e2e92b9b5b24b4c989513bb1d333fd8":{
      "scriptId":"u29"},
    "192f7fbbbb18491f824c61c512287d93":{
      "scriptId":"u30"},
    "879a797992694ea093fbd00ec1d54c7f":{
      "scriptId":"u31"},
    "c8ad6c14c1864f44ae6809c571a75c48":{
      "scriptId":"u32"},
    "35a59415a44b4d6b9519834d861235f3":{
      "scriptId":"u33"},
    "e72c31218e884eeb80ba027768da6dd9":{
      "scriptId":"u34"},
    "2aba03944b99410c92a0daeae3b47559":{
      "scriptId":"u35"},
    "15f7119b298c490aabbcf576b8322d3c":{
      "scriptId":"u36"},
    "84293d3787304c519838c0acde978d24":{
      "scriptId":"u37"},
    "aa453dce3c444f9eb0d271fa617f3685":{
      "scriptId":"u38"},
    "065b261cdad34f829cfa7364f5b84776":{
      "scriptId":"u39"},
    "539237c79bc24168b7c9a7c04b943318":{
      "scriptId":"u40"},
    "99b331cba1784a37b64cdfdc9f28916d":{
      "scriptId":"u41"},
    "377ce0b8ec9642a4816840218656ba47":{
      "scriptId":"u42"},
    "6a931e74daf34a28a2e60280bd97ff9e":{
      "scriptId":"u43"},
    "642fad26a8cd4afc942385576d640a90":{
      "scriptId":"u44"},
    "cb9ae1aec29c496a99a82bb334f9d551":{
      "scriptId":"u45"},
    "3257cda772084b8dbc1499c679ed78f2":{
      "scriptId":"u46"},
    "766a42a927e04ad59242adece750b330":{
      "scriptId":"u47"},
    "00fedd38ae4041cd86a30560c29bdf20":{
      "scriptId":"u48"},
    "c30daff18889494cb0c0da7573608488":{
      "scriptId":"u49"},
    "d598534d4bd640ddb46a08e4238fbb7f":{
      "scriptId":"u50"},
    "8c96335858174bdea405fb91959e2c64":{
      "scriptId":"u51"},
    "d3742f54533340b8b563a7f51982cdd0":{
      "scriptId":"u52"},
    "5283933c9bcf4b48bab36301fe0fffd1":{
      "scriptId":"u53"},
    "1fd39f2018994e0e9f4657a81a8c3171":{
      "scriptId":"u54"},
    "dad931d31de94640a311aed5386c8c77":{
      "scriptId":"u55"},
    "4d5bee13236c43d68223ea6380628e96":{
      "scriptId":"u56"},
    "7f06ddb9196948e887cc81140cce65c4":{
      "scriptId":"u57"},
    "c7fb945d650e4deb9e3c70bf17d372ec":{
      "scriptId":"u58"},
    "897686583e4145c7b97c1467302a42be":{
      "scriptId":"u59"},
    "dcd0d47b990344048f3b652429a494fa":{
      "scriptId":"u60"},
    "83e06133518d40e48f5c8b2f79ecaf0f":{
      "scriptId":"u61"},
    "f89fdefaaf7445d7940960394c247dfe":{
      "scriptId":"u62"},
    "c328d660f7d24a8bafd9b8c171d132ad":{
      "scriptId":"u63"},
    "f48d2ef9ec124e9b82218ac03f2f71cc":{
      "scriptId":"u64"},
    "67511cc2cf6f47d198f3aa61cb2e3e5c":{
      "scriptId":"u65"},
    "5261e700066d4a07b3706ebd637ff290":{
      "scriptId":"u66"},
    "da8f9e085fea4731913470e2ea48eb9c":{
      "scriptId":"u67"},
    "2c040a183027416db62246032503a7e8":{
      "scriptId":"u68"},
    "8d3756173d914c90981f745939954da9":{
      "scriptId":"u69"},
    "80fb0c5b8d1e43118fdcad6f06aa222f":{
      "scriptId":"u70"},
    "76c371cfe91e48c6975cc611df9c65f3":{
      "scriptId":"u71"},
    "4ade55c0fcec42f0b95f06fb0e1d8d26":{
      "scriptId":"u72"},
    "272e12a6f43d46ffa3c486c3c8d816a4":{
      "scriptId":"u73"},
    "901eb6caf0674de78ed97ff6d54190f2":{
      "scriptId":"u74"},
    "4bfb410bd95c4ae9ae9cebad4fee7672":{
      "scriptId":"u75"},
    "b03855078dfe47ec8ec5a956caafe1cb":{
      "scriptId":"u76"},
    "e1ca5625a6ce4acc959079e46c8d4135":{
      "scriptId":"u77"},
    "84f976456c9c4a3d85f0e990366dfb70":{
      "scriptId":"u78"},
    "e6e7df0a24564bd3a335eab1122feb1c":{
      "scriptId":"u79"},
    "e56aa12a790543adb16efa40315e12da":{
      "scriptId":"u80"},
    "12bb0f3bd19e4a4a91e15163ac35c601":{
      "scriptId":"u81"},
    "14fe4fa4408c47f5b45bcd7f519c8cb6":{
      "scriptId":"u82"},
    "e3f17da4725a4eb3a37dafac9b851384":{
      "scriptId":"u83"},
    "481bdc13df49444595c5c7bd06b85b7c":{
      "scriptId":"u84"},
    "28922d4227ae413286edc4eb88ae726f":{
      "scriptId":"u85"},
    "5455110d02494edda47bb840441eedf1":{
      "scriptId":"u86"},
    "0c1a6af7dd2946299e101d60fb791aa6":{
      "scriptId":"u87"},
    "7af961a1a3794542bdf8f82697ff2840":{
      "scriptId":"u88"},
    "5e7151a9040b4e9c9aaaa5208b14a37e":{
      "scriptId":"u89"},
    "e0dd40dc2d454a9384c2a82c7f09b5b9":{
      "scriptId":"u90"},
    "61090560e5f44e88be5c90c44637d8f1":{
      "scriptId":"u91"},
    "ee1553f6f5b849dda2497cf4f9598c19":{
      "scriptId":"u92"},
    "4d82da34f5a7486facd8c09316cccbdf":{
      "scriptId":"u93"},
    "1e558a74f146476d9ff993e2b0eeff37":{
      "scriptId":"u94"},
    "92542a9136e446128a58fb8ed81bb5ea":{
      "scriptId":"u95"},
    "bc5571a94f104dd68b7984cece45eae8":{
      "scriptId":"u96"},
    "966f6bd3aaad49829f9e520458790f19":{
      "scriptId":"u97"},
    "9da275aa29064b418548e4e6dfb7c59d":{
      "scriptId":"u98"},
    "b7f61435eed8414b93966fca6fd8140b":{
      "scriptId":"u99"}}});