$axure.loadCurrentPage({
  "url":"新建elb实例.html",
  "generationDate":new Date(1405317789759.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"521658e5f59940f3be36a282caefe122",
    "type":"Axure:Page",
    "name":"新建ELB实例",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b6328dcc497f4c448e200c660a035109",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":-9,
              "y":70},
            "size":{
              "width":1000,
              "height":690},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b326fe4fd6654d058f917dbb317d8530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":-9,
                  "y":70},
                "size":{
                  "width":1000,
                  "height":690},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建rds实例/u0.png"}},
{
          "id":"07c6d17887b24d62b25933740f87ab69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1000,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a45aeb86ed094c6e9e63a49bf96ae23a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1000,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u2.png"}},
{
          "id":"7c6d70850ba34353b89ddbbdc252abe4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4df8109f95e41b09df2a39d1b0f742a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u4.png"}},
{
          "id":"8d94b2918c2c406b87e3a1b2dc50ca82",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":81,
              "y":25},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fc51c58bcb9429da078a0f87e219340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":25},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5a6c0a04bd148b1b2b70ace340a6a10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":180,
              "y":26},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c33119c8ca84dcda7db582219ca43b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":26},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5470a74175dc4f3cba5436718d04528c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"15b07d892fc54decb7f2f13a0d762478",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":251,
              "y":26},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11cc8f20e50e4186baff374aed155b20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":251,
                  "y":26},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4aeb3b9b07774ab49e45fa16c7086778",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":295,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e4b90f1f51343a8b95c8fd41b791ddf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":295,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"8ddad9d266c44e9a8aa1550f85c0812a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":295,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e807495fa3d4d44bafe3974ff266688",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":295,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"f922640a4310463f9cb926917149f13d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"baf1d47fca284baf84e47adddbd3e456",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":324,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90f71b77e95247f196e0f26120a69a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7771d8632a34035ad1d5306f85303a2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"e86e515326864e9bbc38b445cb33201e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":407,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3203c717f284bf3933435cee0bee36c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e9ef89652344affb3a016fc1f5e8a50",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"2e36e3bf904940bdab4773e765fd8e5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":487,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9884f916cf7a4d1e864c802821264489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"478921daf6ab4630a2e9efed08417140",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"d3b1e8b4579741bbafaf5ebe974e67d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":567,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15a99ca027cc48feb99ddc16d88db82f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":567,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9628f30b22a4400b181d2404da19669",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"ed6582f50b2041f7b6c76274ed27862d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":647,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50fdaaaf6c6d4a5b898d7f517f49736f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":647,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbfe0e9e53f049568f69cc67d901ca2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":252,
              "y":64},
            "size":{
              "width":49,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86bc7af3c51a4b7e9d80e51d1ba221b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":252,
                  "y":64},
                "size":{
                  "width":49,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u32.png"}},
{
          "id":"6be05c5f88834bf4b445568ad26f5ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":765,
              "y":28},
            "size":{
              "width":139,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee87bd8b4cba4552a8afc1e677d8ba12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":765,
                  "y":28},
                "size":{
                  "width":139,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da25a85876df4fb085542cd31d680d82",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":936,
              "y":27},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f201d8a779384c8e9863a6d7df0ba373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":27},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e01f2f18f7ef4f3180043550d54b37ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":381,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5266621bebf43ce933c5a7a82c94ede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":381,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"8f7f935b86534847b431b0106111ce92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":381,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b951c2244fe24a31a80e9ecfc8b74f6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":381,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"367c0a7de0e24940a13bb1a923d21346",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":913,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880a94b9a49d406d957460928ed18e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":913,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"945f27c27f8f4bbe9615d87315ad15ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":913,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39c66bda003e4e3c9631a757282a7aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":913,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"c0c182459111447f8aa0655545766d94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":964,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5932439b5ac404f99a881dd9b8c9c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":964,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"451dfeb78b0846adbbec23506cfb5b4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":964,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1580632d0ab47399ce94b0ea0d4bf1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":964,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"54b9086675c1497a9fc1b48f56241151",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "location":{
              "x":903,
              "y":13},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4aa7abdac894b28b01668c0a92725e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "location":{
                  "x":903,
                  "y":13},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u100.png"}},
{
          "id":"e60362ae2f2b45bfbda443299ac98f25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":30,
              "y":144},
            "size":{
              "width":200,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b253ca7c39904e67b0795785bc74835b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":30,
                  "y":144},
                "size":{
                  "width":200,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u73.png"}},
{
          "id":"480732191d8a475898b1df5dab32b057",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":245,
              "y":145},
            "size":{
              "width":200,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16ff9d50e6c647a3a0b9bf79a62fde64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":245,
                  "y":145},
                "size":{
                  "width":200,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u75.png"}},
{
          "id":"763342d770a64ec997275bd910ae64b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":460,
              "y":145},
            "size":{
              "width":200,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e1703866b424a5f9877fd7b739a19d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":460,
                  "y":145},
                "size":{
                  "width":200,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u75.png"}},
{
          "id":"722a0a676dab436681d1530bde6a6c45",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":70,
              "y":126},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63b19aa2e1244de3992956f512cd0ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":126},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4309f3d39ace4a12b82bac18c5dd0809",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":310,
              "y":125},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0514109eea0e4f1fae5f3b788ea01fb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":125},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb932e8c27f2407093c11a65106e1abb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":524.5,
              "y":125},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21467d90bbf24706b6141bdcf6769dd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":524.5,
                  "y":125},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"922238554ec24ec39dfee6d776d613be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":43,
              "y":176},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"953f3fd3842743d99150e70554e01600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":43,
                  "y":176},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fa4e76796504922879c50bf6d69a2c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":114,
              "y":168},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce258cc365c34621b37109766adf7b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":114,
                  "y":168},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u93.png"}},
{
          "id":"a79f8f181844480b9f8df840584e4722",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":114,
              "y":219},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b657ee63819e467287c1e9f0b1c918a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":114,
                  "y":219},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ebs磁盘/u69.png"}},
{
          "id":"1e2b750079d14e34a29d92c69aeb0e3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":44,
              "y":227},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f65e11cf5de40cea095e010cdeb1e72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":44,
                  "y":227},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f917a6107694de8b682272846f567ef",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":375},
            "size":{
              "width":599,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u164_line.png"}},
{
          "id":"39400df8743d40fb9f144393076dae7a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":444},
            "size":{
              "width":599,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u175_line.png"}},
{
          "id":"19487d2f7554497f9bbd58ea98daf8e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":113,
              "y":469},
            "size":{
              "width":171,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9645aaff459e4f7394c74ecb80065025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":113,
                  "y":469},
                "size":{
                  "width":171,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b38d0642d3c248548f506e4005c690eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":114,
              "y":507},
            "size":{
              "width":170,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49cba23041c244e892b6ad7cb7318be1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":114,
                  "y":507},
                "size":{
                  "width":170,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u178.png"}},
{
          "id":"1b51a48a1a1e493282b14d986611cca2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":30,
              "y":91},
            "size":{
              "width":443,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b02f5a03d4344ce9ae07fd4063466db4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":30,
                  "y":91},
                "size":{
                  "width":443,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd20f8acb72c420083c587ed6e2b3dbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":303,
              "y":469},
            "size":{
              "width":189,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"462ef99d537e470ba5f1bcf3aa904ba5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":303,
                  "y":469},
                "size":{
                  "width":189,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d7f94be0ead482ca5b82905e4192236",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":72,
              "y":345},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9506178ec4bc4dc5bdb8a6dbd92a25d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":72,
                  "y":345},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c815f41d58ed47ad822f67d30c1cf0ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":113,
              "y":345},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5155288f9bf44bebb04556699c3e0158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":113,
                  "y":345},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c20cbb46be44196a9fbde5fc98d9936",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":113,
              "y":400},
            "size":{
              "width":170,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8d5f3b5f1024031bee325338408e97c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":113,
                  "y":400},
                "size":{
                  "width":170,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u136.png"}},
{
          "id":"e1ef583eca2e4bf3954f8367c17e1b8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":408},
            "size":{
              "width":71,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d38d479f8efb489e8834aac6193183fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":408},
                "size":{
                  "width":71,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bb52d16c2f642119191d49d7b790d7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":144,
              "y":400},
            "size":{
              "width":110,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb179ee14bb9496aa66386577eccdfc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":400},
                "size":{
                  "width":110,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u169.png"}},
{
          "id":"fe811000962540d58e5e3104382b2c55",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":124,
              "y":396},
            "size":{
              "width":11,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6628d6d88b43445e825bd295d7bb51a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":396},
                "size":{
                  "width":11,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d7314dbe6ec4939a9ab9c3c9317148a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":262,
              "y":405},
            "size":{
              "width":13,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"895e66292b2d40a99bb609a83f079bc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":262,
                  "y":405},
                "size":{
                  "width":13,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18b41f23c2a5483a98fa122579079cd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":204,
              "y":168},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"512ba918780b4681842bcb55bec2fd9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":204,
                  "y":168},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u95.png"}},
{
          "id":"6423d614c002460684057f32d8b7c6d7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":114,
              "y":263},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe1acc687434cb38563a72a54a8fc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":114,
                  "y":263},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"33ccc5c443f44d08a3335f5c84c6a60e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":132,
              "y":263},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e69c0d8b000440b9a473588554ea608e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":132,
                  "y":263},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44a5beeebb0f4ed5adfa49e383090c05",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":263},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e05d2ecc0f4df1a3ce9c03d177f34b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":263},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ba55224de28148fdb7ebb741cdde564c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":268,
              "y":263},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ca58c9b0dd94ec2a0837769c80b2a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":268,
                  "y":263},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90c81dd3e52b4681bb532055fd82b217",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":114,
              "y":292},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42ba59f5ffe94e74830ef78b6717908f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":114,
                  "y":292},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u113.png"}},
{
          "id":"6c24dd6c270a49dea57fae3665234adb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":234,
              "y":292},
            "size":{
              "width":319,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26261fd004f54cc18a915f7c365b5391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":234,
                  "y":292},
                "size":{
                  "width":319,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u115.png"}},
{
          "id":"183a836f39854517b1e18f0c2ee07cc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":312,
              "y":301},
            "size":{
              "width":39,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ecd8b87dcf4ab3a3241ff2eb1820f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":312,
                  "y":301},
                "size":{
                  "width":39,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56fc65c861924b119ba8aabf301808b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":401,
              "y":301},
            "size":{
              "width":33,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"982fd01dc66d44e69e58547e22900d10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":401,
                  "y":301},
                "size":{
                  "width":33,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1b118ca32d549e0acf491164f969b96",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":500,
              "y":301},
            "size":{
              "width":40,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaee4b386c8a45108163b2004e946a40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":500,
                  "y":301},
                "size":{
                  "width":40,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7ce8de0b83e44a3b83007b459a45528",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":292},
            "size":{
              "width":10,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u123_line.png"}},
{
          "id":"ca20ca179f36420fa310dd375c2a56c9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":292},
            "size":{
              "width":10,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u123_line.png"}},
{
          "id":"0e8a3a03375e4e31a8185d727d15bc48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":288},
            "size":{
              "width":20,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.34901961684227}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f335f96b71b246faa7088c7d618528fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":288},
                "size":{
                  "width":20,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.34901961684227}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u266.png"}},
{
          "id":"32f0f4cd21fe4f87aa362834df08927d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":300},
            "size":{
              "width":10,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u127_line.png"}},
{
          "id":"4a183ed639c14bee9a14addabec59748",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":300},
            "size":{
              "width":10,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u127_line.png"}},
{
          "id":"b7a5097422344cdf863fb5b28d433876",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":563,
              "y":292},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af7abe8ffe31405599efed866ea07a61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Medium', 'Heiti SC Medium', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":563,
                  "y":292},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u271.png"}},
{
          "id":"a741c6f073ea4b169e41e6ff8cd7af1d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":300},
            "size":{
              "width":10,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u127_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b6328dcc497f4c448e200c660a035109":{
      "scriptId":"u0"},
    "b326fe4fd6654d058f917dbb317d8530":{
      "scriptId":"u1"},
    "07c6d17887b24d62b25933740f87ab69":{
      "scriptId":"u2"},
    "a45aeb86ed094c6e9e63a49bf96ae23a":{
      "scriptId":"u3"},
    "7c6d70850ba34353b89ddbbdc252abe4":{
      "scriptId":"u4"},
    "e4df8109f95e41b09df2a39d1b0f742a":{
      "scriptId":"u5"},
    "8d94b2918c2c406b87e3a1b2dc50ca82":{
      "scriptId":"u6"},
    "9fc51c58bcb9429da078a0f87e219340":{
      "scriptId":"u7"},
    "c5a6c0a04bd148b1b2b70ace340a6a10":{
      "scriptId":"u8"},
    "2c33119c8ca84dcda7db582219ca43b3":{
      "scriptId":"u9"},
    "5470a74175dc4f3cba5436718d04528c":{
      "scriptId":"u10"},
    "15b07d892fc54decb7f2f13a0d762478":{
      "scriptId":"u11"},
    "11cc8f20e50e4186baff374aed155b20":{
      "scriptId":"u12"},
    "4aeb3b9b07774ab49e45fa16c7086778":{
      "scriptId":"u13"},
    "5e4b90f1f51343a8b95c8fd41b791ddf":{
      "scriptId":"u14"},
    "8ddad9d266c44e9a8aa1550f85c0812a":{
      "scriptId":"u15"},
    "3e807495fa3d4d44bafe3974ff266688":{
      "scriptId":"u16"},
    "f922640a4310463f9cb926917149f13d":{
      "scriptId":"u17"},
    "baf1d47fca284baf84e47adddbd3e456":{
      "scriptId":"u18"},
    "90f71b77e95247f196e0f26120a69a41":{
      "scriptId":"u19"},
    "f7771d8632a34035ad1d5306f85303a2":{
      "scriptId":"u20"},
    "e86e515326864e9bbc38b445cb33201e":{
      "scriptId":"u21"},
    "b3203c717f284bf3933435cee0bee36c":{
      "scriptId":"u22"},
    "6e9ef89652344affb3a016fc1f5e8a50":{
      "scriptId":"u23"},
    "2e36e3bf904940bdab4773e765fd8e5d":{
      "scriptId":"u24"},
    "9884f916cf7a4d1e864c802821264489":{
      "scriptId":"u25"},
    "478921daf6ab4630a2e9efed08417140":{
      "scriptId":"u26"},
    "d3b1e8b4579741bbafaf5ebe974e67d6":{
      "scriptId":"u27"},
    "15a99ca027cc48feb99ddc16d88db82f":{
      "scriptId":"u28"},
    "d9628f30b22a4400b181d2404da19669":{
      "scriptId":"u29"},
    "ed6582f50b2041f7b6c76274ed27862d":{
      "scriptId":"u30"},
    "50fdaaaf6c6d4a5b898d7f517f49736f":{
      "scriptId":"u31"},
    "dbfe0e9e53f049568f69cc67d901ca2c":{
      "scriptId":"u32"},
    "86bc7af3c51a4b7e9d80e51d1ba221b2":{
      "scriptId":"u33"},
    "6be05c5f88834bf4b445568ad26f5ab9":{
      "scriptId":"u34"},
    "ee87bd8b4cba4552a8afc1e677d8ba12":{
      "scriptId":"u35"},
    "da25a85876df4fb085542cd31d680d82":{
      "scriptId":"u36"},
    "f201d8a779384c8e9863a6d7df0ba373":{
      "scriptId":"u37"},
    "e01f2f18f7ef4f3180043550d54b37ec":{
      "scriptId":"u38"},
    "d5266621bebf43ce933c5a7a82c94ede":{
      "scriptId":"u39"},
    "8f7f935b86534847b431b0106111ce92":{
      "scriptId":"u40"},
    "b951c2244fe24a31a80e9ecfc8b74f6f":{
      "scriptId":"u41"},
    "367c0a7de0e24940a13bb1a923d21346":{
      "scriptId":"u42"},
    "880a94b9a49d406d957460928ed18e15":{
      "scriptId":"u43"},
    "945f27c27f8f4bbe9615d87315ad15ce":{
      "scriptId":"u44"},
    "39c66bda003e4e3c9631a757282a7aa0":{
      "scriptId":"u45"},
    "c0c182459111447f8aa0655545766d94":{
      "scriptId":"u46"},
    "e5932439b5ac404f99a881dd9b8c9c8c":{
      "scriptId":"u47"},
    "451dfeb78b0846adbbec23506cfb5b4d":{
      "scriptId":"u48"},
    "b1580632d0ab47399ce94b0ea0d4bf1f":{
      "scriptId":"u49"},
    "54b9086675c1497a9fc1b48f56241151":{
      "scriptId":"u50"},
    "a4aa7abdac894b28b01668c0a92725e6":{
      "scriptId":"u51"},
    "e60362ae2f2b45bfbda443299ac98f25":{
      "scriptId":"u52"},
    "b253ca7c39904e67b0795785bc74835b":{
      "scriptId":"u53"},
    "480732191d8a475898b1df5dab32b057":{
      "scriptId":"u54"},
    "16ff9d50e6c647a3a0b9bf79a62fde64":{
      "scriptId":"u55"},
    "763342d770a64ec997275bd910ae64b5":{
      "scriptId":"u56"},
    "1e1703866b424a5f9877fd7b739a19d0":{
      "scriptId":"u57"},
    "722a0a676dab436681d1530bde6a6c45":{
      "scriptId":"u58"},
    "63b19aa2e1244de3992956f512cd0ad6":{
      "scriptId":"u59"},
    "4309f3d39ace4a12b82bac18c5dd0809":{
      "scriptId":"u60"},
    "0514109eea0e4f1fae5f3b788ea01fb3":{
      "scriptId":"u61"},
    "eb932e8c27f2407093c11a65106e1abb":{
      "scriptId":"u62"},
    "21467d90bbf24706b6141bdcf6769dd0":{
      "scriptId":"u63"},
    "922238554ec24ec39dfee6d776d613be":{
      "scriptId":"u64"},
    "953f3fd3842743d99150e70554e01600":{
      "scriptId":"u65"},
    "3fa4e76796504922879c50bf6d69a2c4":{
      "scriptId":"u66"},
    "ce258cc365c34621b37109766adf7b1e":{
      "scriptId":"u67"},
    "a79f8f181844480b9f8df840584e4722":{
      "scriptId":"u68"},
    "b657ee63819e467287c1e9f0b1c918a1":{
      "scriptId":"u69"},
    "1e2b750079d14e34a29d92c69aeb0e3a":{
      "scriptId":"u70"},
    "3f65e11cf5de40cea095e010cdeb1e72":{
      "scriptId":"u71"},
    "2f917a6107694de8b682272846f567ef":{
      "scriptId":"u72"},
    "39400df8743d40fb9f144393076dae7a":{
      "scriptId":"u73"},
    "19487d2f7554497f9bbd58ea98daf8e2":{
      "scriptId":"u74"},
    "9645aaff459e4f7394c74ecb80065025":{
      "scriptId":"u75"},
    "b38d0642d3c248548f506e4005c690eb":{
      "scriptId":"u76"},
    "49cba23041c244e892b6ad7cb7318be1":{
      "scriptId":"u77"},
    "1b51a48a1a1e493282b14d986611cca2":{
      "scriptId":"u78"},
    "b02f5a03d4344ce9ae07fd4063466db4":{
      "scriptId":"u79"},
    "cd20f8acb72c420083c587ed6e2b3dbe":{
      "scriptId":"u80"},
    "462ef99d537e470ba5f1bcf3aa904ba5":{
      "scriptId":"u81"},
    "7d7f94be0ead482ca5b82905e4192236":{
      "scriptId":"u82"},
    "9506178ec4bc4dc5bdb8a6dbd92a25d3":{
      "scriptId":"u83"},
    "c815f41d58ed47ad822f67d30c1cf0ce":{
      "scriptId":"u84"},
    "5155288f9bf44bebb04556699c3e0158":{
      "scriptId":"u85"},
    "6c20cbb46be44196a9fbde5fc98d9936":{
      "scriptId":"u86"},
    "f8d5f3b5f1024031bee325338408e97c":{
      "scriptId":"u87"},
    "e1ef583eca2e4bf3954f8367c17e1b8e":{
      "scriptId":"u88"},
    "d38d479f8efb489e8834aac6193183fb":{
      "scriptId":"u89"},
    "4bb52d16c2f642119191d49d7b790d7f":{
      "scriptId":"u90"},
    "bb179ee14bb9496aa66386577eccdfc1":{
      "scriptId":"u91"},
    "fe811000962540d58e5e3104382b2c55":{
      "scriptId":"u92"},
    "6628d6d88b43445e825bd295d7bb51a4":{
      "scriptId":"u93"},
    "5d7314dbe6ec4939a9ab9c3c9317148a":{
      "scriptId":"u94"},
    "895e66292b2d40a99bb609a83f079bc0":{
      "scriptId":"u95"},
    "18b41f23c2a5483a98fa122579079cd0":{
      "scriptId":"u96"},
    "512ba918780b4681842bcb55bec2fd9d":{
      "scriptId":"u97"},
    "6423d614c002460684057f32d8b7c6d7":{
      "scriptId":"u98"},
    "afe1acc687434cb38563a72a54a8fc5e":{
      "scriptId":"u99"},
    "33ccc5c443f44d08a3335f5c84c6a60e":{
      "scriptId":"u100"},
    "e69c0d8b000440b9a473588554ea608e":{
      "scriptId":"u101"},
    "44a5beeebb0f4ed5adfa49e383090c05":{
      "scriptId":"u102"},
    "71e05d2ecc0f4df1a3ce9c03d177f34b":{
      "scriptId":"u103"},
    "ba55224de28148fdb7ebb741cdde564c":{
      "scriptId":"u104"},
    "2ca58c9b0dd94ec2a0837769c80b2a09":{
      "scriptId":"u105"},
    "90c81dd3e52b4681bb532055fd82b217":{
      "scriptId":"u106"},
    "42ba59f5ffe94e74830ef78b6717908f":{
      "scriptId":"u107"},
    "6c24dd6c270a49dea57fae3665234adb":{
      "scriptId":"u108"},
    "26261fd004f54cc18a915f7c365b5391":{
      "scriptId":"u109"},
    "183a836f39854517b1e18f0c2ee07cc7":{
      "scriptId":"u110"},
    "f1ecd8b87dcf4ab3a3241ff2eb1820f0":{
      "scriptId":"u111"},
    "56fc65c861924b119ba8aabf301808b2":{
      "scriptId":"u112"},
    "982fd01dc66d44e69e58547e22900d10":{
      "scriptId":"u113"},
    "a1b118ca32d549e0acf491164f969b96":{
      "scriptId":"u114"},
    "eaee4b386c8a45108163b2004e946a40":{
      "scriptId":"u115"},
    "f7ce8de0b83e44a3b83007b459a45528":{
      "scriptId":"u116"},
    "ca20ca179f36420fa310dd375c2a56c9":{
      "scriptId":"u117"},
    "0e8a3a03375e4e31a8185d727d15bc48":{
      "scriptId":"u118"},
    "f335f96b71b246faa7088c7d618528fe":{
      "scriptId":"u119"},
    "32f0f4cd21fe4f87aa362834df08927d":{
      "scriptId":"u120"},
    "4a183ed639c14bee9a14addabec59748":{
      "scriptId":"u121"},
    "b7a5097422344cdf863fb5b28d433876":{
      "scriptId":"u122"},
    "af7abe8ffe31405599efed866ea07a61":{
      "scriptId":"u123"},
    "a741c6f073ea4b169e41e6ff8cd7af1d":{
      "scriptId":"u124"}}});