$axure.loadCurrentPage({
  "url":"监控_3.html",
  "generationDate":new Date(1405317789393.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"623c213c24144dc2820ef46c7adbdb33",
    "type":"Axure:Page",
    "name":"监控",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f06b5b950cda469d95016f1dce0d2568",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":1000,
              "height":740},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"061924f500c341058cef8e9d139280e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":1000,
                  "height":740},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加步骤/u0.png"}},
{
          "id":"cf6ce0779aa1468585de37c74fd55281",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1000,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d7d5afa35d94b4dba96bc5b9056ac86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1000,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u2.png"}},
{
          "id":"ee7690eec00d49fcba7b86f49765a34a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f87c74dbdc194acb9a87bf00ad789b9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u4.png"}},
{
          "id":"f0a74e15c8594b89825edd22f9850f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":81,
              "y":25},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d523d04278724a9b91af6975d79c08bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":25},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"870b1672d49b4a628856b2fe533fa98b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":180,
              "y":26},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d066e855bb1e4a269d70194a1d1bfa42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":26},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d073f344e28345f2b8d333add159fff4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"fa2f64b190394819b557c8ee2f567c54",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":251,
              "y":26},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"720602b244d9477d837ac0bc9875e2a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":251,
                  "y":26},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48947a8772ac493fa48c21693f80e131",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":295,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c416c3501040e7abf3f6fbbc2ecd71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":295,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"a057241436084a61880bcccccd104301",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":295,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd5eb3a999c443583e6711a298c8d8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":295,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"c623777c3d814ba9a31e0527f2f14a65",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"f85a283ecfd34935ad703dbe66608586",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":324,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e6ad605ca784892913bb98282818019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15498d6bc69a4711b386e370c1cda0fe",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"aebcdfea23f74c18906df7ba5c0ede7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":407,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42fce0c89b984e6eba4adea12995cc0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a468c7a8d9654872ae68c8eb67e5c810",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"2e46d83d91224300ad174b437128044a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":487,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"963f6ca76525448db32f2276b62f20bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93571161e19c42bc865dfdd884c648b3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"99731f1186a7468ab560bf00edc5b6c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":567,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5cfc0748e2b4b81870ceb697251a31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":567,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b96d0988e6274b91a6a1ab1804ab6218",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"51af980ffa2c42ab8073f4b84da9ad13",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":647,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e36fbc3e66704bb9802cc665581e11c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":647,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8cf83f6035f4c0bb5b9c3a55fbd6999",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":252,
              "y":64},
            "size":{
              "width":49,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77b9c08071674256b393cae657c663ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":252,
                  "y":64},
                "size":{
                  "width":49,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u32.png"}},
{
          "id":"748961e436b94fb88d0fc09f91c1054e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":765,
              "y":28},
            "size":{
              "width":139,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19c3ab85838949e9a2b31b95172d2f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":765,
                  "y":28},
                "size":{
                  "width":139,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3a3496c5cf44eabb13c24008d6d234f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":936,
              "y":27},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c00afc9a6fd449c2919394358974a47e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":27},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7d6b1a8af194fafb20579b4cc22941a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":381,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad11c92bee444e5ca4f64d2897a893d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":381,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"4fda2d68bbf84fc2bf71649f00904713",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":381,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36ea8ad98e4a4b06a3cb39109d636365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":381,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"f6bbcb64f06c46a59a8a86fc908524a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":913,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f568ba09484821b7bfe158cd1958a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":913,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"9e45eee53d9a41da94ce8da3d7555720",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":913,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca2ade6729942af9873eb03e8e4c3d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":913,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"42e991bb37124785b1364a9d3b2c49ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":964,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb59efbf8724aba91db07b13eb262a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":964,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"9763ab3582ce4e2b9f586d330b14c54c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":964,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e4bc9a3d05142539c82e92b2f2e24f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":964,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"51da3f5432c648a48e4d1e073879fbf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "location":{
              "x":903,
              "y":13},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4358f7770d954f738e47eeee839295e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "location":{
                  "x":903,
                  "y":13},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u100.png"}},
{
          "id":"d857d54598fa40fca0c43ce912b91758",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":30,
              "y":91},
            "size":{
              "width":443,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"781c903aea93469a8ce29231c9fe1182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":30,
                  "y":91},
                "size":{
                  "width":443,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4aaf0c225cbe43a3841ed641881f5c50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":28,
              "y":121},
            "size":{
              "width":40,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b27155427eb549a6a1c69b5018929232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":28,
                  "y":121},
                "size":{
                  "width":40,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u77.png"}},
{
          "id":"934aec839751429c8c4fe4627c6dd16e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":69,
              "y":133},
            "size":{
              "width":200,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93d323398034d05bca103e8a3d9235a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":69,
                  "y":133},
                "size":{
                  "width":200,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7da3ca43db0a46bb960e87c732aa0903",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":268,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"562e26bb8b484d95a032fba25c8d1235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":268,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u88.png"}},
{
          "id":"2d4114d3f0124bc4ab58d9b03b3d814f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":30,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4e2b01a75f14a8880c581c7d66365c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":30,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u88.png"}},
{
          "id":"ccc58aec13264d35879a9f8197cbb6ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":149,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3b5b6f7aeb4b048f24a88a2992f8ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":149,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u88.png"}},
{
          "id":"030a8abd0c3e48a695f2e7b6af04600d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":218},
            "size":{
              "width":940,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/集群列表（已建集群）/u80_line.png"}},
{
          "id":"d8e4242b965e4046b433f8900e1aa600",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":387,
              "y":179},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f50041e82ad449e3904ff8f96a9fe0de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":387,
                  "y":179},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ebs磁盘快照/u139.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f06b5b950cda469d95016f1dce0d2568":{
      "scriptId":"u0"},
    "061924f500c341058cef8e9d139280e2":{
      "scriptId":"u1"},
    "cf6ce0779aa1468585de37c74fd55281":{
      "scriptId":"u2"},
    "3d7d5afa35d94b4dba96bc5b9056ac86":{
      "scriptId":"u3"},
    "ee7690eec00d49fcba7b86f49765a34a":{
      "scriptId":"u4"},
    "f87c74dbdc194acb9a87bf00ad789b9b":{
      "scriptId":"u5"},
    "f0a74e15c8594b89825edd22f9850f1c":{
      "scriptId":"u6"},
    "d523d04278724a9b91af6975d79c08bd":{
      "scriptId":"u7"},
    "870b1672d49b4a628856b2fe533fa98b":{
      "scriptId":"u8"},
    "d066e855bb1e4a269d70194a1d1bfa42":{
      "scriptId":"u9"},
    "d073f344e28345f2b8d333add159fff4":{
      "scriptId":"u10"},
    "fa2f64b190394819b557c8ee2f567c54":{
      "scriptId":"u11"},
    "720602b244d9477d837ac0bc9875e2a6":{
      "scriptId":"u12"},
    "48947a8772ac493fa48c21693f80e131":{
      "scriptId":"u13"},
    "94c416c3501040e7abf3f6fbbc2ecd71":{
      "scriptId":"u14"},
    "a057241436084a61880bcccccd104301":{
      "scriptId":"u15"},
    "8cd5eb3a999c443583e6711a298c8d8f":{
      "scriptId":"u16"},
    "c623777c3d814ba9a31e0527f2f14a65":{
      "scriptId":"u17"},
    "f85a283ecfd34935ad703dbe66608586":{
      "scriptId":"u18"},
    "5e6ad605ca784892913bb98282818019":{
      "scriptId":"u19"},
    "15498d6bc69a4711b386e370c1cda0fe":{
      "scriptId":"u20"},
    "aebcdfea23f74c18906df7ba5c0ede7d":{
      "scriptId":"u21"},
    "42fce0c89b984e6eba4adea12995cc0a":{
      "scriptId":"u22"},
    "a468c7a8d9654872ae68c8eb67e5c810":{
      "scriptId":"u23"},
    "2e46d83d91224300ad174b437128044a":{
      "scriptId":"u24"},
    "963f6ca76525448db32f2276b62f20bd":{
      "scriptId":"u25"},
    "93571161e19c42bc865dfdd884c648b3":{
      "scriptId":"u26"},
    "99731f1186a7468ab560bf00edc5b6c0":{
      "scriptId":"u27"},
    "e5cfc0748e2b4b81870ceb697251a31a":{
      "scriptId":"u28"},
    "b96d0988e6274b91a6a1ab1804ab6218":{
      "scriptId":"u29"},
    "51af980ffa2c42ab8073f4b84da9ad13":{
      "scriptId":"u30"},
    "e36fbc3e66704bb9802cc665581e11c1":{
      "scriptId":"u31"},
    "b8cf83f6035f4c0bb5b9c3a55fbd6999":{
      "scriptId":"u32"},
    "77b9c08071674256b393cae657c663ce":{
      "scriptId":"u33"},
    "748961e436b94fb88d0fc09f91c1054e":{
      "scriptId":"u34"},
    "19c3ab85838949e9a2b31b95172d2f0d":{
      "scriptId":"u35"},
    "d3a3496c5cf44eabb13c24008d6d234f":{
      "scriptId":"u36"},
    "c00afc9a6fd449c2919394358974a47e":{
      "scriptId":"u37"},
    "e7d6b1a8af194fafb20579b4cc22941a":{
      "scriptId":"u38"},
    "ad11c92bee444e5ca4f64d2897a893d6":{
      "scriptId":"u39"},
    "4fda2d68bbf84fc2bf71649f00904713":{
      "scriptId":"u40"},
    "36ea8ad98e4a4b06a3cb39109d636365":{
      "scriptId":"u41"},
    "f6bbcb64f06c46a59a8a86fc908524a4":{
      "scriptId":"u42"},
    "21f568ba09484821b7bfe158cd1958a3":{
      "scriptId":"u43"},
    "9e45eee53d9a41da94ce8da3d7555720":{
      "scriptId":"u44"},
    "cca2ade6729942af9873eb03e8e4c3d2":{
      "scriptId":"u45"},
    "42e991bb37124785b1364a9d3b2c49ce":{
      "scriptId":"u46"},
    "bbb59efbf8724aba91db07b13eb262a0":{
      "scriptId":"u47"},
    "9763ab3582ce4e2b9f586d330b14c54c":{
      "scriptId":"u48"},
    "7e4bc9a3d05142539c82e92b2f2e24f0":{
      "scriptId":"u49"},
    "51da3f5432c648a48e4d1e073879fbf0":{
      "scriptId":"u50"},
    "4358f7770d954f738e47eeee839295e1":{
      "scriptId":"u51"},
    "d857d54598fa40fca0c43ce912b91758":{
      "scriptId":"u52"},
    "781c903aea93469a8ce29231c9fe1182":{
      "scriptId":"u53"},
    "4aaf0c225cbe43a3841ed641881f5c50":{
      "scriptId":"u54"},
    "b27155427eb549a6a1c69b5018929232":{
      "scriptId":"u55"},
    "934aec839751429c8c4fe4627c6dd16e":{
      "scriptId":"u56"},
    "f93d323398034d05bca103e8a3d9235a":{
      "scriptId":"u57"},
    "7da3ca43db0a46bb960e87c732aa0903":{
      "scriptId":"u58"},
    "562e26bb8b484d95a032fba25c8d1235":{
      "scriptId":"u59"},
    "2d4114d3f0124bc4ab58d9b03b3d814f":{
      "scriptId":"u60"},
    "a4e2b01a75f14a8880c581c7d66365c2":{
      "scriptId":"u61"},
    "ccc58aec13264d35879a9f8197cbb6ce":{
      "scriptId":"u62"},
    "7c3b5b6f7aeb4b048f24a88a2992f8ed":{
      "scriptId":"u63"},
    "030a8abd0c3e48a695f2e7b6af04600d":{
      "scriptId":"u64"},
    "d8e4242b965e4046b433f8900e1aa600":{
      "scriptId":"u65"},
    "f50041e82ad449e3904ff8f96a9fe0de":{
      "scriptId":"u66"}}});