$axure.loadCurrentPage({
  "url":"首页样式二.html",
  "generationDate":new Date(1405317736032.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2689e746557d490e940f950ef40dc8ef",
    "type":"Axure:Page",
    "name":"首页样式二",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2226cd05557742e2a1a1383a38ed8c3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ca144b49e17412ca5f5fc68ddf08fa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u0.png"}},
{
          "id":"aa5153d9469d491099af6215e5db4773",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"24px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":45,
              "y":25},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d3110fe43145ceb09c49229d6b93f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"24px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":45,
                  "y":25},
                "size":{
                  "width":73,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74aea013ad544421b671c62822cf9b49",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":1020,
              "height":801}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "url":"页面隐藏_1.html",
            "includeVariables":true}},
{
          "id":"3868719f52b34a09b1e241ddf057dd59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":999,
              "y":69},
            "size":{
              "width":21,
              "height":784}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a6025f1a7024c3c8fad4b9d1c89f073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":999,
                  "y":69},
                "size":{
                  "width":21,
                  "height":784}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u5.png"}},
{
          "id":"4ac32f5174934f7b856991dc548142f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":60},
            "size":{
              "width":21,
              "height":810},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12c2e14afb9647539e9c0471c892b57f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":60},
                "size":{
                  "width":21,
                  "height":810},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u7.png"}},
{
          "id":"e2d4ad3e01284b74810f7d7e8e6113cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":853},
            "size":{
              "width":1000,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af6e6019c2f42138f3b5bf8d56ab5aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":853},
                "size":{
                  "width":1000,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u9.png"}},
{
          "id":"fbe8d0c9c4db4192a6cd41b0dd7c1ef8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":854},
            "size":{
              "width":1000,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade6ae6ebe5842de94c25ef7454ef249",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":854},
                "size":{
                  "width":1000,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u11.png"}},
{
          "id":"5b0d00c60c7443dca345638d09ac411b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":206,
              "y":29},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faf937dd8aa04483826624d7b4490651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":206,
                  "y":29},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65224f7e23fc46ce87f7cde3813e11f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":402,
              "y":29},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f3efe0c27544daa53f52c7feaa90cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":402,
                  "y":29},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e40f190c959c4b04ad6552c6df356299",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":305,
              "y":29},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7d543ae0574410b837258b6cb9d3909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":305,
                  "y":29},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e147a37639f64c5a932720330f99bc34",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":512,
              "y":29},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d98bfdd5d93245688219c2d2b4cc10f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":512,
                  "y":29},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fd1e7932458456e9ffd10f46e3faae5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":944,
              "y":26},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c626ebd1b9b46a4aab43444cc12b247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":944,
                  "y":26},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2112e94f17ca474382cd32a63a0ad2d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":860,
              "y":26},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acbba5ee4d3040cbb14928c7ef0e5392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":860,
                  "y":26},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d6d9d313ca04d00a414a23a10f546df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":827,
              "y":21},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f504af8bcde48ff887d512ee7df4543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":827,
                  "y":21},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u25.png"}},
{
          "id":"8da52f212187414783b5c29121316b7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":20},
            "size":{
              "width":29,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc3c65d35d8442e7b38f57a59684f692",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":20},
                "size":{
                  "width":29,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u27.png"}},
{
          "id":"857cdacbfa67474c850eef978fbdc5fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":835,
              "y":26},
            "size":{
              "width":11,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41413df037174b719f8fae6dccc7d517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":835,
                  "y":26},
                "size":{
                  "width":11,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u29.png"}},
{
          "id":"5564d1f1206b43c0afde6b57805bdbdc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1efbd6ed66e4c849643b415595d1b20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"bdc4def31f914f68b8c5057888812a81",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":147,
              "y":29},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb72180dfcf5469682688e7827677be5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":147,
                  "y":29},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2783a91ed37245e68184d1835d38bcc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86c006e30b6549ce8f0bd51241159ea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"8018e9a4efd5486e86326a30367fd17c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4d1a3a2247a44debc4a44686f3bba15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"db0f821364104f709fd99523a12ec352",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ef4be772e514c83952f943c7da78762",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"b5918cc46a1343c89f9b536cd9ed4e3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":138,
              "y":64},
            "size":{
              "width":50,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5137c6840884f919192e7ede7f9b12c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":138,
                  "y":64},
                "size":{
                  "width":50,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u41.png"}},
{
          "id":"d4fbd8e3c07f40a9bc43e18e62cc83f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":336},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ed9a29dc4db4f58aff8055139ac260a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":336},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u43.png"}},
{
          "id":"9afc1edd6bd743bf80e23b7d7ef8759a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1039,
              "y":348},
            "size":{
              "width":34,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db46befabec473aa7b6e5c66608b887",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1039,
                  "y":348},
                "size":{
                  "width":34,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u45.png"}},
{
          "id":"65a99d6f68844db089418ca5285dc713",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":385},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ecb804ef78412ba0eea568f417fc47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":385},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u43.png"}},
{
          "id":"9044017234fa46518b1bc9895aefaa61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1043,
              "y":401},
            "size":{
              "width":26,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0338f94f5f4642948610a9ad41f5e07e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1043,
                  "y":401},
                "size":{
                  "width":26,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u49.png"}},
{
          "id":"adbfa910ab704f8f9dfde5a325bab0c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1043,
              "y":409},
            "size":{
              "width":26,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"484c9c9a4ad846b0a9ae0a35c05492cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1043,
                  "y":409},
                "size":{
                  "width":26,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u51.png"}},
{
          "id":"45ec162312d74696a739dec2506bd95e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":895,
              "y":10},
            "size":{
              "width":95,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71ad7319ca424d5fa4d5f41cda74e7f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":895,
                  "y":10},
                "size":{
                  "width":95,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆页",
                      "target":{
                        "targetType":"page",
                        "url":"登陆页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2226cd05557742e2a1a1383a38ed8c3a":{
      "scriptId":"u0"},
    "9ca144b49e17412ca5f5fc68ddf08fa8":{
      "scriptId":"u1"},
    "aa5153d9469d491099af6215e5db4773":{
      "scriptId":"u2"},
    "b9d3110fe43145ceb09c49229d6b93f5":{
      "scriptId":"u3"},
    "74aea013ad544421b671c62822cf9b49":{
      "scriptId":"u4"},
    "3868719f52b34a09b1e241ddf057dd59":{
      "scriptId":"u5"},
    "9a6025f1a7024c3c8fad4b9d1c89f073":{
      "scriptId":"u6"},
    "4ac32f5174934f7b856991dc548142f4":{
      "scriptId":"u7"},
    "12c2e14afb9647539e9c0471c892b57f":{
      "scriptId":"u8"},
    "e2d4ad3e01284b74810f7d7e8e6113cf":{
      "scriptId":"u9"},
    "3af6e6019c2f42138f3b5bf8d56ab5aa":{
      "scriptId":"u10"},
    "fbe8d0c9c4db4192a6cd41b0dd7c1ef8":{
      "scriptId":"u11"},
    "ade6ae6ebe5842de94c25ef7454ef249":{
      "scriptId":"u12"},
    "5b0d00c60c7443dca345638d09ac411b":{
      "scriptId":"u13"},
    "faf937dd8aa04483826624d7b4490651":{
      "scriptId":"u14"},
    "65224f7e23fc46ce87f7cde3813e11f2":{
      "scriptId":"u15"},
    "31f3efe0c27544daa53f52c7feaa90cc":{
      "scriptId":"u16"},
    "e40f190c959c4b04ad6552c6df356299":{
      "scriptId":"u17"},
    "d7d543ae0574410b837258b6cb9d3909":{
      "scriptId":"u18"},
    "e147a37639f64c5a932720330f99bc34":{
      "scriptId":"u19"},
    "d98bfdd5d93245688219c2d2b4cc10f9":{
      "scriptId":"u20"},
    "7fd1e7932458456e9ffd10f46e3faae5":{
      "scriptId":"u21"},
    "3c626ebd1b9b46a4aab43444cc12b247":{
      "scriptId":"u22"},
    "2112e94f17ca474382cd32a63a0ad2d7":{
      "scriptId":"u23"},
    "acbba5ee4d3040cbb14928c7ef0e5392":{
      "scriptId":"u24"},
    "9d6d9d313ca04d00a414a23a10f546df":{
      "scriptId":"u25"},
    "7f504af8bcde48ff887d512ee7df4543":{
      "scriptId":"u26"},
    "8da52f212187414783b5c29121316b7c":{
      "scriptId":"u27"},
    "bc3c65d35d8442e7b38f57a59684f692":{
      "scriptId":"u28"},
    "857cdacbfa67474c850eef978fbdc5fe":{
      "scriptId":"u29"},
    "41413df037174b719f8fae6dccc7d517":{
      "scriptId":"u30"},
    "5564d1f1206b43c0afde6b57805bdbdc":{
      "scriptId":"u31"},
    "d1efbd6ed66e4c849643b415595d1b20":{
      "scriptId":"u32"},
    "bdc4def31f914f68b8c5057888812a81":{
      "scriptId":"u33"},
    "bb72180dfcf5469682688e7827677be5":{
      "scriptId":"u34"},
    "2783a91ed37245e68184d1835d38bcc5":{
      "scriptId":"u35"},
    "86c006e30b6549ce8f0bd51241159ea1":{
      "scriptId":"u36"},
    "8018e9a4efd5486e86326a30367fd17c":{
      "scriptId":"u37"},
    "b4d1a3a2247a44debc4a44686f3bba15":{
      "scriptId":"u38"},
    "db0f821364104f709fd99523a12ec352":{
      "scriptId":"u39"},
    "9ef4be772e514c83952f943c7da78762":{
      "scriptId":"u40"},
    "b5918cc46a1343c89f9b536cd9ed4e3d":{
      "scriptId":"u41"},
    "b5137c6840884f919192e7ede7f9b12c":{
      "scriptId":"u42"},
    "d4fbd8e3c07f40a9bc43e18e62cc83f0":{
      "scriptId":"u43"},
    "8ed9a29dc4db4f58aff8055139ac260a":{
      "scriptId":"u44"},
    "9afc1edd6bd743bf80e23b7d7ef8759a":{
      "scriptId":"u45"},
    "1db46befabec473aa7b6e5c66608b887":{
      "scriptId":"u46"},
    "65a99d6f68844db089418ca5285dc713":{
      "scriptId":"u47"},
    "d1ecb804ef78412ba0eea568f417fc47":{
      "scriptId":"u48"},
    "9044017234fa46518b1bc9895aefaa61":{
      "scriptId":"u49"},
    "0338f94f5f4642948610a9ad41f5e07e":{
      "scriptId":"u50"},
    "adbfa910ab704f8f9dfde5a325bab0c8":{
      "scriptId":"u51"},
    "484c9c9a4ad846b0a9ae0a35c05492cf":{
      "scriptId":"u52"},
    "45ec162312d74696a739dec2506bd95e":{
      "scriptId":"u53"},
    "71ad7319ca424d5fa4d5f41cda74e7f1":{
      "scriptId":"u54"}}});