$axure.loadCurrentPage({
  "url":"首页样式一.html",
  "generationDate":new Date(1405317734910.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cf6c6baabfeb43278eb21b6f2733add2",
    "type":"Axure:Page",
    "name":"首页样式一",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1d8d702de63b4c3ea016adc04c7fcb7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73557030e78a4162be9c5ef0b02d5699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u0.png"}},
{
          "id":"96a546385fd14cc3b877a094cb748ed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"24px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":45,
              "y":25},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15903bdb97e54fe09fe397415428b57c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"24px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":45,
                  "y":25},
                "size":{
                  "width":73,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70b6ec8cb7814252bce38cdcd1f008ab",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":1020,
              "height":801}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "url":"页面隐藏.html",
            "includeVariables":true}},
{
          "id":"466c3892537a418aad7f1b7abdc72f58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":999,
              "y":69},
            "size":{
              "width":21,
              "height":784}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ed65e6189104bf4907790025145f559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":999,
                  "y":69},
                "size":{
                  "width":21,
                  "height":784}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u5.png"}},
{
          "id":"dbb11196f0f8405dab6bf773c5e3c734",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":60},
            "size":{
              "width":21,
              "height":810},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a60cb6914744d9990c70367bf303b16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1000,
                  "y":60},
                "size":{
                  "width":21,
                  "height":810},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u7.png"}},
{
          "id":"58c7f13095c8482abffa8abd2c52fe75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":853},
            "size":{
              "width":1000,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37713c64a02a4ccda57ade0c7e6fddac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":853},
                "size":{
                  "width":1000,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u9.png"}},
{
          "id":"04b23a5d8b544ba4a17b64c01f7e589a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":854},
            "size":{
              "width":1000,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c4b2f00b3be4e75936d09fc7f26d1db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":854},
                "size":{
                  "width":1000,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u11.png"}},
{
          "id":"9a7f293790494f89a03952579628d47f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":206,
              "y":29},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03fcd6bd2f2c4d01bb7d358d8546ff6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":206,
                  "y":29},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88d549b3b1034fc0848b609a8d555bab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":402,
              "y":29},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"993aa0d3f7744d84b2322ab110f39378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":402,
                  "y":29},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"640dc5f9a4e84a549d329acf79b7ea2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":305,
              "y":29},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"721c1ef32de04285bb799adf7274e98c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":305,
                  "y":29},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84d31fe825ae4df6a4cfdb9ae71cbac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":512,
              "y":29},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068c00ba23974ca6b010101a636a1ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":512,
                  "y":29},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d23de5c1cf974cb3a47cce4708fe02f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":944,
              "y":26},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2904708975084d4ba1ab60d1d145565c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":944,
                  "y":26},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ddfc49848e0488b9af59e3032c09a61",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":860,
              "y":26},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9fd5a9a8c64e74b9ffdfe0369395f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":860,
                  "y":26},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11005266dd8d4b6391941b1819bd4685",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":827,
              "y":21},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33f723c9d3ca4444b1546ca5b896d573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":827,
                  "y":21},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u25.png"}},
{
          "id":"5ce4c12ceeac4a509542c3aca0c33b7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":20},
            "size":{
              "width":29,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4296449b3dd74da9bd3ecebb8503cba5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":20},
                "size":{
                  "width":29,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u27.png"}},
{
          "id":"396f005bc7fc49709efeb805a2ee6cad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":835,
              "y":26},
            "size":{
              "width":11,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8da8e2104d1c465cab8025bd5ac6000a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":835,
                  "y":26},
                "size":{
                  "width":11,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u29.png"}},
{
          "id":"96e67e048ab848f397abb1147558271b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09d4277cc1564ffb949799065282d901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"c403b5b1b41a4c31b1b3a758ee9a9b92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":147,
              "y":29},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a389c85c6e348228ef2f61bc148c258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":147,
                  "y":29},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4593c6e03b6471b8eee5c228b45008f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f98076876f46d6b17c460e24c6bb7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"f60298f48731412d8909d635fe6748a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af3449b973843c58f9626927a540a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"0709476f7052401bbb3f2e13f7156494",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dece2f8025754c9c9eaf0ad29f9bedd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"837eb4dfde4345e3a51e758fb608e992",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":138,
              "y":64},
            "size":{
              "width":50,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4f7e6e89564a84b1c313c3cf7cf683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":138,
                  "y":64},
                "size":{
                  "width":50,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u41.png"}},
{
          "id":"667657925cf94809af13365a5be39ec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":336},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0bb92a915c146bb802363a02530d159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":336},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u43.png"}},
{
          "id":"53f72f238868471b99602f69d65549d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1039,
              "y":348},
            "size":{
              "width":34,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a29abc657734e8fa048286e99b1439b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1039,
                  "y":348},
                "size":{
                  "width":34,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u45.png"}},
{
          "id":"46737ef05d604ca4a60f6137f727023e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":385},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6293df90259d4ff6963109ece2c9761a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":385},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u43.png"}},
{
          "id":"c668ce0dd239421e90c2200da98ac449",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1043,
              "y":401},
            "size":{
              "width":26,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adea1c0eaf744460a736a1062b40513d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1043,
                  "y":401},
                "size":{
                  "width":26,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u49.png"}},
{
          "id":"207483694c8e4c2cacf0abe98fe92563",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1043,
              "y":409},
            "size":{
              "width":26,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24500a31f6ca47ad9f6e579317fa3b67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1043,
                  "y":409},
                "size":{
                  "width":26,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u51.png"}},
{
          "id":"1dffd3351837485c87ea9616b5d60068",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":0},
            "size":{
              "width":1000,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"980d1e6132924f17a5944ebfa8592fbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1060,
                  "y":0},
                "size":{
                  "width":1000,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u0.png"}},
{
          "id":"e9fe11be52394852bab407f3421bf7bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"24px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":1105,
              "y":25},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5964f81724cd4d34a085d92da7c6fcfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"24px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":1105,
                  "y":25},
                "size":{
                  "width":73,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61e0986aad73425f86d2b25b2b4f45c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":2004,
              "y":26},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b841983f188f4f358fe3709a146f2da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":2004,
                  "y":26},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b03928bf4c33467e8f7ae82270d372f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1970,
              "y":20},
            "size":{
              "width":29,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f68080a65fe24aeea1e182360096fd95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1970,
                  "y":20},
                "size":{
                  "width":29,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u27.png"}},
{
          "id":"424d0af3bafb47eead79916da418ca4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1325,
              "y":30},
            "size":{
              "width":414,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39f617ea3f6c471a934d427a1d8e804c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1325,
                  "y":30},
                "size":{
                  "width":414,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"007d1c156f154466831c5ddd741abb01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":1742,
              "y":18},
            "size":{
              "width":81,
              "height":40},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac1ea8b902545158c5371f6961eb89a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":1742,
                  "y":18},
                "size":{
                  "width":81,
                  "height":40},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u63.png"}},
{
          "id":"cfb5fe124b274af7acba9fec6ba62f8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":110},
            "size":{
              "width":1000,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19257bcf629f4d548f102ed3a718e9fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1060,
                  "y":110},
                "size":{
                  "width":1000,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u0.png"}},
{
          "id":"aee9ada52789466ba42ba1820baf1ddb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"24px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":1105,
              "y":135},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"410d553f64834080ad8ad66ce6a2865d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"24px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":1105,
                  "y":135},
                "size":{
                  "width":73,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d431c78ac75471eb8bd9bd0a259108e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1266,
              "y":139},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77796a86260c4841aca79a6ef3d743ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1266,
                  "y":139},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e65e3cd270b241a39a3281ea410e337b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1462,
              "y":139},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5c4ec728eab4a82b93de43385ed751f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1462,
                  "y":139},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"852abac30d244e85b02708ecf944b997",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1365,
              "y":139},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2e9ad6daca646489e1c47a62fa0fe92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1365,
                  "y":139},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a874453c8446430ab28538b124813db2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1572,
              "y":139},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fba4253586e43d195c1b2799e120c39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1572,
                  "y":139},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52483d7ec0e54128b0bec80436de7959",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":2004,
              "y":136},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa612a5f2ae466cb0e8245384c25285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":2004,
                  "y":136},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"299d4df5d9ec48f2bb445d6dd4fdd6ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1920,
              "y":136},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde8ff4d6e664e04b9fed46d43cf31f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1920,
                  "y":136},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4629305434974476b7377962611417a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1887,
              "y":131},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52567c035c15434ea42c98a226033eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1887,
                  "y":131},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u81.png"}},
{
          "id":"767b037dc010465490db48525c16e502",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1970,
              "y":130},
            "size":{
              "width":29,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f189f29f4a7407fa5d056ab0c70ee85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1970,
                  "y":130},
                "size":{
                  "width":29,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u27.png"}},
{
          "id":"88579c89ed8541a5ae3fdd5df8e1924d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1895,
              "y":136},
            "size":{
              "width":11,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a342963c0e70480f94f786f3bb7217c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1895,
                  "y":136},
                "size":{
                  "width":11,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u29.png"}},
{
          "id":"01abaad4027e4eb8ac2f5912f5e31ae8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1330,
              "y":140},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0bdfb2cbc3f4966a81dea6f1daca25b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1330,
                  "y":140},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"01936dba60494feca4f9291cd16266ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1207,
              "y":139},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"476ad57645e14745a082c539a7d05016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1207,
                  "y":139},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d4dc28a042d40528f82c9bf23c8d2c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1430,
              "y":140},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae16f74dda524538949875f416ddb01d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1430,
                  "y":140},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"6ce7090147664084862e39eb011f4c7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1541,
              "y":140},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f80cd29541634f949f80a9651154b6be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1541,
                  "y":140},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"25f4310ab290400b80845ace5d3a7fd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1653,
              "y":140},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b34bcf9772e14eea855851d829201100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1653,
                  "y":140},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"c677c31ad94a4ce1841cebab640e6a70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1198,
              "y":174},
            "size":{
              "width":50,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6377382ad3146bdb2a09eb1c8afbf72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1198,
                  "y":174},
                "size":{
                  "width":50,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u41.png"}},
{
          "id":"d874101849ba41c18bdd4b0ec1c5d1df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1206,
              "y":180},
            "size":{
              "width":683,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9cff29866264f988e243ab6b8fac2e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1206,
                  "y":180},
                "size":{
                  "width":683,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u99.png"}},
{
          "id":"6ac60105a911462dbcaf28f8853f025c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":1298,
              "y":202},
            "size":{
              "width":414,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66acedbd30cd43deabe82f16d41e6389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":1298,
                  "y":202},
                "size":{
                  "width":414,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b10025353e94ac69ed2ab887ed9b0c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":1715,
              "y":190},
            "size":{
              "width":81,
              "height":40},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bfe2dda4b6a4b0ba65d98f09a2e9fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":1715,
                  "y":190},
                "size":{
                  "width":81,
                  "height":40},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u63.png"}},
{
          "id":"4bedad076fb24499b13fc2e26793faaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":895,
              "y":10},
            "size":{
              "width":95,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de20014697014a3d922d1229a327ace4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":895,
                  "y":10},
                "size":{
                  "width":95,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆页",
                      "target":{
                        "targetType":"page",
                        "url":"登陆页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1d8d702de63b4c3ea016adc04c7fcb7e":{
      "scriptId":"u0"},
    "73557030e78a4162be9c5ef0b02d5699":{
      "scriptId":"u1"},
    "96a546385fd14cc3b877a094cb748ed7":{
      "scriptId":"u2"},
    "15903bdb97e54fe09fe397415428b57c":{
      "scriptId":"u3"},
    "70b6ec8cb7814252bce38cdcd1f008ab":{
      "scriptId":"u4"},
    "466c3892537a418aad7f1b7abdc72f58":{
      "scriptId":"u5"},
    "0ed65e6189104bf4907790025145f559":{
      "scriptId":"u6"},
    "dbb11196f0f8405dab6bf773c5e3c734":{
      "scriptId":"u7"},
    "8a60cb6914744d9990c70367bf303b16":{
      "scriptId":"u8"},
    "58c7f13095c8482abffa8abd2c52fe75":{
      "scriptId":"u9"},
    "37713c64a02a4ccda57ade0c7e6fddac":{
      "scriptId":"u10"},
    "04b23a5d8b544ba4a17b64c01f7e589a":{
      "scriptId":"u11"},
    "7c4b2f00b3be4e75936d09fc7f26d1db":{
      "scriptId":"u12"},
    "9a7f293790494f89a03952579628d47f":{
      "scriptId":"u13"},
    "03fcd6bd2f2c4d01bb7d358d8546ff6b":{
      "scriptId":"u14"},
    "88d549b3b1034fc0848b609a8d555bab":{
      "scriptId":"u15"},
    "993aa0d3f7744d84b2322ab110f39378":{
      "scriptId":"u16"},
    "640dc5f9a4e84a549d329acf79b7ea2f":{
      "scriptId":"u17"},
    "721c1ef32de04285bb799adf7274e98c":{
      "scriptId":"u18"},
    "84d31fe825ae4df6a4cfdb9ae71cbac6":{
      "scriptId":"u19"},
    "068c00ba23974ca6b010101a636a1ddc":{
      "scriptId":"u20"},
    "d23de5c1cf974cb3a47cce4708fe02f3":{
      "scriptId":"u21"},
    "2904708975084d4ba1ab60d1d145565c":{
      "scriptId":"u22"},
    "6ddfc49848e0488b9af59e3032c09a61":{
      "scriptId":"u23"},
    "0a9fd5a9a8c64e74b9ffdfe0369395f0":{
      "scriptId":"u24"},
    "11005266dd8d4b6391941b1819bd4685":{
      "scriptId":"u25"},
    "33f723c9d3ca4444b1546ca5b896d573":{
      "scriptId":"u26"},
    "5ce4c12ceeac4a509542c3aca0c33b7a":{
      "scriptId":"u27"},
    "4296449b3dd74da9bd3ecebb8503cba5":{
      "scriptId":"u28"},
    "396f005bc7fc49709efeb805a2ee6cad":{
      "scriptId":"u29"},
    "8da8e2104d1c465cab8025bd5ac6000a":{
      "scriptId":"u30"},
    "96e67e048ab848f397abb1147558271b":{
      "scriptId":"u31"},
    "09d4277cc1564ffb949799065282d901":{
      "scriptId":"u32"},
    "c403b5b1b41a4c31b1b3a758ee9a9b92":{
      "scriptId":"u33"},
    "9a389c85c6e348228ef2f61bc148c258":{
      "scriptId":"u34"},
    "d4593c6e03b6471b8eee5c228b45008f":{
      "scriptId":"u35"},
    "78f98076876f46d6b17c460e24c6bb7b":{
      "scriptId":"u36"},
    "f60298f48731412d8909d635fe6748a7":{
      "scriptId":"u37"},
    "3af3449b973843c58f9626927a540a94":{
      "scriptId":"u38"},
    "0709476f7052401bbb3f2e13f7156494":{
      "scriptId":"u39"},
    "dece2f8025754c9c9eaf0ad29f9bedd1":{
      "scriptId":"u40"},
    "837eb4dfde4345e3a51e758fb608e992":{
      "scriptId":"u41"},
    "6b4f7e6e89564a84b1c313c3cf7cf683":{
      "scriptId":"u42"},
    "667657925cf94809af13365a5be39ec8":{
      "scriptId":"u43"},
    "b0bb92a915c146bb802363a02530d159":{
      "scriptId":"u44"},
    "53f72f238868471b99602f69d65549d1":{
      "scriptId":"u45"},
    "4a29abc657734e8fa048286e99b1439b":{
      "scriptId":"u46"},
    "46737ef05d604ca4a60f6137f727023e":{
      "scriptId":"u47"},
    "6293df90259d4ff6963109ece2c9761a":{
      "scriptId":"u48"},
    "c668ce0dd239421e90c2200da98ac449":{
      "scriptId":"u49"},
    "adea1c0eaf744460a736a1062b40513d":{
      "scriptId":"u50"},
    "207483694c8e4c2cacf0abe98fe92563":{
      "scriptId":"u51"},
    "24500a31f6ca47ad9f6e579317fa3b67":{
      "scriptId":"u52"},
    "1dffd3351837485c87ea9616b5d60068":{
      "scriptId":"u53"},
    "980d1e6132924f17a5944ebfa8592fbd":{
      "scriptId":"u54"},
    "e9fe11be52394852bab407f3421bf7bd":{
      "scriptId":"u55"},
    "5964f81724cd4d34a085d92da7c6fcfd":{
      "scriptId":"u56"},
    "61e0986aad73425f86d2b25b2b4f45c3":{
      "scriptId":"u57"},
    "b841983f188f4f358fe3709a146f2da5":{
      "scriptId":"u58"},
    "b03928bf4c33467e8f7ae82270d372f1":{
      "scriptId":"u59"},
    "f68080a65fe24aeea1e182360096fd95":{
      "scriptId":"u60"},
    "424d0af3bafb47eead79916da418ca4e":{
      "scriptId":"u61"},
    "39f617ea3f6c471a934d427a1d8e804c":{
      "scriptId":"u62"},
    "007d1c156f154466831c5ddd741abb01":{
      "scriptId":"u63"},
    "dac1ea8b902545158c5371f6961eb89a":{
      "scriptId":"u64"},
    "cfb5fe124b274af7acba9fec6ba62f8d":{
      "scriptId":"u65"},
    "19257bcf629f4d548f102ed3a718e9fb":{
      "scriptId":"u66"},
    "aee9ada52789466ba42ba1820baf1ddb":{
      "scriptId":"u67"},
    "410d553f64834080ad8ad66ce6a2865d":{
      "scriptId":"u68"},
    "5d431c78ac75471eb8bd9bd0a259108e":{
      "scriptId":"u69"},
    "77796a86260c4841aca79a6ef3d743ee":{
      "scriptId":"u70"},
    "e65e3cd270b241a39a3281ea410e337b":{
      "scriptId":"u71"},
    "c5c4ec728eab4a82b93de43385ed751f":{
      "scriptId":"u72"},
    "852abac30d244e85b02708ecf944b997":{
      "scriptId":"u73"},
    "e2e9ad6daca646489e1c47a62fa0fe92":{
      "scriptId":"u74"},
    "a874453c8446430ab28538b124813db2":{
      "scriptId":"u75"},
    "8fba4253586e43d195c1b2799e120c39":{
      "scriptId":"u76"},
    "52483d7ec0e54128b0bec80436de7959":{
      "scriptId":"u77"},
    "afa612a5f2ae466cb0e8245384c25285":{
      "scriptId":"u78"},
    "299d4df5d9ec48f2bb445d6dd4fdd6ad":{
      "scriptId":"u79"},
    "bde8ff4d6e664e04b9fed46d43cf31f9":{
      "scriptId":"u80"},
    "4629305434974476b7377962611417a1":{
      "scriptId":"u81"},
    "52567c035c15434ea42c98a226033eec":{
      "scriptId":"u82"},
    "767b037dc010465490db48525c16e502":{
      "scriptId":"u83"},
    "2f189f29f4a7407fa5d056ab0c70ee85":{
      "scriptId":"u84"},
    "88579c89ed8541a5ae3fdd5df8e1924d":{
      "scriptId":"u85"},
    "a342963c0e70480f94f786f3bb7217c3":{
      "scriptId":"u86"},
    "01abaad4027e4eb8ac2f5912f5e31ae8":{
      "scriptId":"u87"},
    "d0bdfb2cbc3f4966a81dea6f1daca25b":{
      "scriptId":"u88"},
    "01936dba60494feca4f9291cd16266ee":{
      "scriptId":"u89"},
    "476ad57645e14745a082c539a7d05016":{
      "scriptId":"u90"},
    "5d4dc28a042d40528f82c9bf23c8d2c1":{
      "scriptId":"u91"},
    "ae16f74dda524538949875f416ddb01d":{
      "scriptId":"u92"},
    "6ce7090147664084862e39eb011f4c7e":{
      "scriptId":"u93"},
    "f80cd29541634f949f80a9651154b6be":{
      "scriptId":"u94"},
    "25f4310ab290400b80845ace5d3a7fd9":{
      "scriptId":"u95"},
    "b34bcf9772e14eea855851d829201100":{
      "scriptId":"u96"},
    "c677c31ad94a4ce1841cebab640e6a70":{
      "scriptId":"u97"},
    "e6377382ad3146bdb2a09eb1c8afbf72":{
      "scriptId":"u98"},
    "d874101849ba41c18bdd4b0ec1c5d1df":{
      "scriptId":"u99"},
    "c9cff29866264f988e243ab6b8fac2e4":{
      "scriptId":"u100"},
    "6ac60105a911462dbcaf28f8853f025c":{
      "scriptId":"u101"},
    "66acedbd30cd43deabe82f16d41e6389":{
      "scriptId":"u102"},
    "4b10025353e94ac69ed2ab887ed9b0c8":{
      "scriptId":"u103"},
    "5bfe2dda4b6a4b0ba65d98f09a2e9fbe":{
      "scriptId":"u104"},
    "4bedad076fb24499b13fc2e26793faaf":{
      "scriptId":"u105"},
    "de20014697014a3d922d1229a327ace4":{
      "scriptId":"u106"}}});