$axure.loadCurrentPage({
  "url":"查看.html",
  "generationDate":new Date(1405317800102.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"be8535df54614ce784f06390ebc57bf8",
    "type":"Axure:Page",
    "name":"查看",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dd2bff3eccf14e779243370df5827588",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":1000,
              "height":740},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3dd08e5a6842cc82261f76284ec58d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":1000,
                  "height":740},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详情/u0.png"}},
{
          "id":"567452394c4e4d43b3e95176757a39cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1000,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da03ff165b464b6084f9c1feb2cfaefc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1000,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u2.png"}},
{
          "id":"7bf887319dd2406ab778bab1e5e51bbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"549de16419e544b486769dc747b8d521",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u4.png"}},
{
          "id":"4cc82422a4df4480b7728f2f81f66ab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":81,
              "y":25},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dfdf6b30f4c4a1abe34e0c047e65bc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":25},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a3a7277d85a4ed0a2938c2f452942d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":180,
              "y":26},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8be31bf3dae9433ea15e80c5502adc68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":26},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc13979fa7c741dc880773c9f21d57e7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"07a4516e34434fe6bf5b6d294a56e115",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":251,
              "y":26},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c9b787e43524bf5ad45e9d78aefd76c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":251,
                  "y":26},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2e9498cb6804289b31abd89c223a82e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":295,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93b17f1fd47048258b7ada6cab6bd0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":295,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"8894c1955775425eb8dc96f08e5ae435",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":295,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2228777e3d8b448dad109a9adffd402c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":295,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"7845f1fc5abe4ab88398faf7ab9811df",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"258da340b3ab4504b7288c7da19674be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":324,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ccc544b9713416aa97a45f38301e044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8556d7e6891244208068755f9bba935e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"864b164ab2254b94b50b3a9025f5acfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":407,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa4517d9f70b4e71871c368437e64288",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f08c9b912fd64923afa7ba492b22c199",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"650f462ed14448fab909aecb09f53529",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":487,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c4600d1b7c47568b94c301cc9cc734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a6a02a8031447c395218ee4c8bb74db",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"bc33add67c6d4cd490fc974a4a7d6dc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":567,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0a20c056a3a482b992d4b381fda1eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":567,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a6f134c581641a4b947a7de6db81147",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":406,
              "y":64},
            "size":{
              "width":58,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ad50303a7441d5b1414649673b4f5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":406,
                  "y":64},
                "size":{
                  "width":58,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u29.png"}},
{
          "id":"1b896a6555744b5e95610722653991b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":765,
              "y":28},
            "size":{
              "width":139,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14ca690e1159465f967e89e1cfcce25d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":765,
                  "y":28},
                "size":{
                  "width":139,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66cf5c05d2f04f8190f65d029f449034",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":936,
              "y":27},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ae6c1bbbf74c6bb6bf8a6e8b3b929f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":27},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c32f08919d67407bb24b493911233c7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":381,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9172fa36848f43548af06e2a7e54113e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":381,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"80ceff815a2f4dc0a35c33073b3323e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":381,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee026e93abd14a0eadd1de570366933c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":381,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"c6ad439395e3439f9bc4cfce55dcfda2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":913,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cb91bff99ea4efc8377c6f562b41673",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":913,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"dd53669dae12429ba887075b9231d5b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":913,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d817bf8baf44692a0d48288092ba37a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":913,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"7aaf48b9ebaf438680f9a1a32da83beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":964,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da83984a0cd94d6c94e4739df88ca546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":964,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"c70af1e96de04adda5bc1cebcbbf5255",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":964,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5714ec311f6345d1972893ee0451a4a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":964,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"1d2c9e3cf56e4b6ebc1362134565b772",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":200,
              "height":740},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8de511c5267f4262933d4017ed157267",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":200,
                  "height":740},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u47.png"}},
{
          "id":"f3075f309eaf41bf854fb050a617c82a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":31,
              "y":149},
            "size":{
              "width":29,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9f23e0d7e014216b8a8089ef7eb7299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":31,
                  "y":149},
                "size":{
                  "width":29,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u52.png"}},
{
          "id":"39d6592ae87a47e59e3b18591a6a580c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF95A4B8,
              "opacity":1},
            "location":{
              "x":70,
              "y":157},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30c9391bfd684203afbc19fa5335fa1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF95A4B8,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":157},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3d605c64e674f398b42b27c830e394f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":185},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u56_line.png"}},
{
          "id":"111fdea149c94f1dbb50c0a24d990e31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":32,
              "y":206},
            "size":{
              "width":27,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd681c9cf2a546fb8494ec8b3d530841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":32,
                  "y":206},
                "size":{
                  "width":27,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u57.png"}},
{
          "id":"c326fcd8f28344f78fb1eb3485489ea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF32445B,
              "opacity":1},
            "location":{
              "x":70,
              "y":215},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506c8be9b1ec46c984b041ab8fb14216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF32445B,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":215},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b07777a57a54f7fa94a26bfb29f4b9c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":245},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u56_line.png"}},
{
          "id":"3d696eaf82f24c3cb1790826d3f96845",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "location":{
              "x":903,
              "y":13},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"312d122051e0448aab7281b900e25e58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "location":{
                  "x":903,
                  "y":13},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u100.png"}},
{
          "id":"232e256f0e914644a607ef6d92f543f9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":125},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u56_line.png"}},
{
          "id":"11afc4cb490d48e7ae81b0f8ef91f29a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF32445B,
              "opacity":1},
            "location":{
              "x":33,
              "y":92},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5177273033a744dc8a58d2fc6fe797e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF32445B,
                  "opacity":1},
                "location":{
                  "x":33,
                  "y":92},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebaacf6a91d643df8701494a0caaec8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":185,
              "y":149},
            "size":{
              "width":36,
              "height":32},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b29971999bc44aa92fa7b7b6398f7b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":185,
                  "y":149},
                "size":{
                  "width":36,
                  "height":32},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u214.png"}},
{
          "id":"921081e29d594a58ad33032bed05c077",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":200,
              "y":145},
            "size":{
              "width":23,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d6c68c9f0ea4f54bdcc6d3f0474ce3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":200,
                  "y":145},
                "size":{
                  "width":23,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u216.png"}},
{
          "id":"42b0ddde2bd84767b9580a89b2721d30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFDCE4EA},
            "location":{
              "x":194,
              "y":161},
            "size":{
              "width":6,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDCE4EA},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da4f3c845aac4a9c83a6afb20a288061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA},
                "location":{
                  "x":194,
                  "y":161},
                "size":{
                  "width":6,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDCE4EA},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u218.png"}},
{
          "id":"cfd89b99dc8543b3962680cfbeb4e40d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":230,
              "y":130},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44f19aac7726406bb039cadcb75c48b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":230,
                  "y":130},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例详情/u88.png"}},
{
          "id":"5c30d799ba5149728feb97174eef839d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":169},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"68f498efb0b449d99cccbd6a0e10e2d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":349,
              "y":130},
            "size":{
              "width":100,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c30ff88cb443e6b8c682f8174fea61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":349,
                  "y":130},
                "size":{
                  "width":100,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ebs磁盘快照/u139.png"}},
{
          "id":"570f29c8219d4cc39422852655c43f5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":899,
              "y":86},
            "size":{
              "width":71,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ec4352bab0478880a8f5b28ce15373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":899,
                  "y":86},
                "size":{
                  "width":71,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实例/u91.png"}},
{
          "id":"452be70160e4454ca6d72795668ab8ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":909,
              "y":92},
            "size":{
              "width":16,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27194b1f963e4ef1831c06e910e1ae18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":909,
                  "y":92},
                "size":{
                  "width":16,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u319.png"}},
{
          "id":"cc88c830a5514707b37f02589e4586b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":934,
              "y":95},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74a95fd3d48f47139a53c66ce71fa06e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":934,
                  "y":95},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be914ea7b49d4892acb42fd43112f64f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":93},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50cfab7f721749469d59244edc6c2dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":93},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a489718d55304dfbb5945b1487c8254a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":194},
            "size":{
              "width":250,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5a58bd9987f4f01a429e3e6ec3a452b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":194},
                "size":{
                  "width":250,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4554b6aa7484015ad750854b73e7a0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":229},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6961f98b2ad743018f1214c1ebcd0ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":229},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d65380fd182744bea960a29fefffd9d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":890,
              "y":223},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7d1d32d3484988babd024878d04fd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":890,
                  "y":223},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u93.png"}},
{
          "id":"e2a2d7092a8949f3970eea5a853543b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":266},
            "size":{
              "width":157,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3786fe04d9a04a289468b48dc3b2de8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":266},
                "size":{
                  "width":157,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec870642343c44429d2c729f8337515e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":299},
            "size":{
              "width":115,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9815e1e4c6be4ba69a88f483d1959413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":299},
                "size":{
                  "width":115,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2544e1ad47614693a7945e3f0db8ebfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":332},
            "size":{
              "width":61,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e53340cb974453e8da656add16983e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":332},
                "size":{
                  "width":61,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"437deee6003b4db780d2584141433fec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":360},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"e7884f9eb3584ed89a7006d402ff39a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":241,
              "y":377},
            "size":{
              "width":161,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d114c525f4475187b51588406ba544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":241,
                  "y":377},
                "size":{
                  "width":161,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aad5bce083d4809ada57ab0e930ce15",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":417,
              "y":377},
            "size":{
              "width":161,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31d38a5a9d54c3297565efea18c7cc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":417,
                  "y":377},
                "size":{
                  "width":161,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c14e89a89f0d4eb8ad6accb9e08a10ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":603,
              "y":377},
            "size":{
              "width":161,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195f92916ff74e329ca29f61a8c7e59a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":603,
                  "y":377},
                "size":{
                  "width":161,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9027f099c374076a9ef666a24caa6b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":789.5,
              "y":377},
            "size":{
              "width":85,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0398f51a786a4ffc9c5a0349b77ee25e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":789.5,
                  "y":377},
                "size":{
                  "width":85,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce6b9a27ef614daab9ab8f6ed544b0e7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":366},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u289_line.png"}},
{
          "id":"f392bd92b31b482f97d7689056c28f6a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":587,
              "y":366},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u289_line.png"}},
{
          "id":"f730d017bf5a4941baf1d6aca08ae0f6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":774.5,
              "y":366},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u289_line.png"}},
{
          "id":"7a6351b89fee482098dd6b2e4b95b14e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":241,
              "y":427},
            "size":{
              "width":161,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57a3cc3b53fd43d49e9fa425772f0e0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":241,
                  "y":427},
                "size":{
                  "width":161,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8014e4b164144ead9f1bd45f912f58d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":416,
              "y":416},
            "size":{
              "width":91,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9800bc08117481885fc6566f79f2bc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":416,
                  "y":416},
                "size":{
                  "width":91,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f1963c85618425eafd528d6961f985e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":790.5,
              "y":416},
            "size":{
              "width":104,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4449eae1c6a49d1a348f5da179ef418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":790.5,
                  "y":416},
                "size":{
                  "width":104,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34ee0ba8bab04cc59ac04d1edacb35c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":603,
              "y":415},
            "size":{
              "width":124,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7983623e8ff4c93b50dd24a34f43556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":603,
                  "y":415},
                "size":{
                  "width":124,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a16cd78b96647659f7c20b4579c5a51",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":395},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"3ddca6b7a37148d380474c1bc1f0012c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":416,
              "y":438},
            "size":{
              "width":91,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec8c306c5b704f10a8ca720624702a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":416,
                  "y":438},
                "size":{
                  "width":91,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ef9a41dd67546c1a8af1866c1e1bab3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":790,
              "y":438},
            "size":{
              "width":104,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35bcdaf6e678403dbce1e285254a6146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":790,
                  "y":438},
                "size":{
                  "width":104,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e95cf4130de463fb47deaf2ac9d3aeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":603,
              "y":437},
            "size":{
              "width":124,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adde0f7075184c2dbcf9b434b607800d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":603,
                  "y":437},
                "size":{
                  "width":124,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75264ec03cd844f78b56872c77239714",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":459},
            "size":{
              "width":740,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/实例/u97_line.png"}},
{
          "id":"e99b7a8a46b2453db07a5ed8005229a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":790,
              "y":484},
            "size":{
              "width":104,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a4f8309ba4249d38003439536b381eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":790,
                  "y":484},
                "size":{
                  "width":104,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b27d40ae2d464d9ebd348b32439d3fd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":760,
              "y":488},
            "size":{
              "width":104,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf5376fdc37f4dbd9ac44c26cf060bec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":760,
                  "y":488},
                "size":{
                  "width":104,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dd2bff3eccf14e779243370df5827588":{
      "scriptId":"u0"},
    "9b3dd08e5a6842cc82261f76284ec58d":{
      "scriptId":"u1"},
    "567452394c4e4d43b3e95176757a39cd":{
      "scriptId":"u2"},
    "da03ff165b464b6084f9c1feb2cfaefc":{
      "scriptId":"u3"},
    "7bf887319dd2406ab778bab1e5e51bbb":{
      "scriptId":"u4"},
    "549de16419e544b486769dc747b8d521":{
      "scriptId":"u5"},
    "4cc82422a4df4480b7728f2f81f66ab4":{
      "scriptId":"u6"},
    "2dfdf6b30f4c4a1abe34e0c047e65bc2":{
      "scriptId":"u7"},
    "3a3a7277d85a4ed0a2938c2f452942d8":{
      "scriptId":"u8"},
    "8be31bf3dae9433ea15e80c5502adc68":{
      "scriptId":"u9"},
    "bc13979fa7c741dc880773c9f21d57e7":{
      "scriptId":"u10"},
    "07a4516e34434fe6bf5b6d294a56e115":{
      "scriptId":"u11"},
    "0c9b787e43524bf5ad45e9d78aefd76c":{
      "scriptId":"u12"},
    "a2e9498cb6804289b31abd89c223a82e":{
      "scriptId":"u13"},
    "93b17f1fd47048258b7ada6cab6bd0b9":{
      "scriptId":"u14"},
    "8894c1955775425eb8dc96f08e5ae435":{
      "scriptId":"u15"},
    "2228777e3d8b448dad109a9adffd402c":{
      "scriptId":"u16"},
    "7845f1fc5abe4ab88398faf7ab9811df":{
      "scriptId":"u17"},
    "258da340b3ab4504b7288c7da19674be":{
      "scriptId":"u18"},
    "9ccc544b9713416aa97a45f38301e044":{
      "scriptId":"u19"},
    "8556d7e6891244208068755f9bba935e":{
      "scriptId":"u20"},
    "864b164ab2254b94b50b3a9025f5acfb":{
      "scriptId":"u21"},
    "aa4517d9f70b4e71871c368437e64288":{
      "scriptId":"u22"},
    "f08c9b912fd64923afa7ba492b22c199":{
      "scriptId":"u23"},
    "650f462ed14448fab909aecb09f53529":{
      "scriptId":"u24"},
    "62c4600d1b7c47568b94c301cc9cc734":{
      "scriptId":"u25"},
    "4a6a02a8031447c395218ee4c8bb74db":{
      "scriptId":"u26"},
    "bc33add67c6d4cd490fc974a4a7d6dc4":{
      "scriptId":"u27"},
    "d0a20c056a3a482b992d4b381fda1eb3":{
      "scriptId":"u28"},
    "2a6f134c581641a4b947a7de6db81147":{
      "scriptId":"u29"},
    "20ad50303a7441d5b1414649673b4f5c":{
      "scriptId":"u30"},
    "1b896a6555744b5e95610722653991b5":{
      "scriptId":"u31"},
    "14ca690e1159465f967e89e1cfcce25d":{
      "scriptId":"u32"},
    "66cf5c05d2f04f8190f65d029f449034":{
      "scriptId":"u33"},
    "79ae6c1bbbf74c6bb6bf8a6e8b3b929f":{
      "scriptId":"u34"},
    "c32f08919d67407bb24b493911233c7d":{
      "scriptId":"u35"},
    "9172fa36848f43548af06e2a7e54113e":{
      "scriptId":"u36"},
    "80ceff815a2f4dc0a35c33073b3323e4":{
      "scriptId":"u37"},
    "ee026e93abd14a0eadd1de570366933c":{
      "scriptId":"u38"},
    "c6ad439395e3439f9bc4cfce55dcfda2":{
      "scriptId":"u39"},
    "7cb91bff99ea4efc8377c6f562b41673":{
      "scriptId":"u40"},
    "dd53669dae12429ba887075b9231d5b3":{
      "scriptId":"u41"},
    "7d817bf8baf44692a0d48288092ba37a":{
      "scriptId":"u42"},
    "7aaf48b9ebaf438680f9a1a32da83beb":{
      "scriptId":"u43"},
    "da83984a0cd94d6c94e4739df88ca546":{
      "scriptId":"u44"},
    "c70af1e96de04adda5bc1cebcbbf5255":{
      "scriptId":"u45"},
    "5714ec311f6345d1972893ee0451a4a4":{
      "scriptId":"u46"},
    "1d2c9e3cf56e4b6ebc1362134565b772":{
      "scriptId":"u47"},
    "8de511c5267f4262933d4017ed157267":{
      "scriptId":"u48"},
    "f3075f309eaf41bf854fb050a617c82a":{
      "scriptId":"u49"},
    "e9f23e0d7e014216b8a8089ef7eb7299":{
      "scriptId":"u50"},
    "39d6592ae87a47e59e3b18591a6a580c":{
      "scriptId":"u51"},
    "30c9391bfd684203afbc19fa5335fa1a":{
      "scriptId":"u52"},
    "b3d605c64e674f398b42b27c830e394f":{
      "scriptId":"u53"},
    "111fdea149c94f1dbb50c0a24d990e31":{
      "scriptId":"u54"},
    "cd681c9cf2a546fb8494ec8b3d530841":{
      "scriptId":"u55"},
    "c326fcd8f28344f78fb1eb3485489ea1":{
      "scriptId":"u56"},
    "506c8be9b1ec46c984b041ab8fb14216":{
      "scriptId":"u57"},
    "4b07777a57a54f7fa94a26bfb29f4b9c":{
      "scriptId":"u58"},
    "3d696eaf82f24c3cb1790826d3f96845":{
      "scriptId":"u59"},
    "312d122051e0448aab7281b900e25e58":{
      "scriptId":"u60"},
    "232e256f0e914644a607ef6d92f543f9":{
      "scriptId":"u61"},
    "11afc4cb490d48e7ae81b0f8ef91f29a":{
      "scriptId":"u62"},
    "5177273033a744dc8a58d2fc6fe797e9":{
      "scriptId":"u63"},
    "ebaacf6a91d643df8701494a0caaec8a":{
      "scriptId":"u64"},
    "9b29971999bc44aa92fa7b7b6398f7b3":{
      "scriptId":"u65"},
    "921081e29d594a58ad33032bed05c077":{
      "scriptId":"u66"},
    "3d6c68c9f0ea4f54bdcc6d3f0474ce3c":{
      "scriptId":"u67"},
    "42b0ddde2bd84767b9580a89b2721d30":{
      "scriptId":"u68"},
    "da4f3c845aac4a9c83a6afb20a288061":{
      "scriptId":"u69"},
    "cfd89b99dc8543b3962680cfbeb4e40d":{
      "scriptId":"u70"},
    "44f19aac7726406bb039cadcb75c48b2":{
      "scriptId":"u71"},
    "5c30d799ba5149728feb97174eef839d":{
      "scriptId":"u72"},
    "68f498efb0b449d99cccbd6a0e10e2d6":{
      "scriptId":"u73"},
    "66c30ff88cb443e6b8c682f8174fea61":{
      "scriptId":"u74"},
    "570f29c8219d4cc39422852655c43f5e":{
      "scriptId":"u75"},
    "20ec4352bab0478880a8f5b28ce15373":{
      "scriptId":"u76"},
    "452be70160e4454ca6d72795668ab8ab":{
      "scriptId":"u77"},
    "27194b1f963e4ef1831c06e910e1ae18":{
      "scriptId":"u78"},
    "cc88c830a5514707b37f02589e4586b8":{
      "scriptId":"u79"},
    "74a95fd3d48f47139a53c66ce71fa06e":{
      "scriptId":"u80"},
    "be914ea7b49d4892acb42fd43112f64f":{
      "scriptId":"u81"},
    "50cfab7f721749469d59244edc6c2dac":{
      "scriptId":"u82"},
    "a489718d55304dfbb5945b1487c8254a":{
      "scriptId":"u83"},
    "e5a58bd9987f4f01a429e3e6ec3a452b":{
      "scriptId":"u84"},
    "c4554b6aa7484015ad750854b73e7a0c":{
      "scriptId":"u85"},
    "6961f98b2ad743018f1214c1ebcd0ac5":{
      "scriptId":"u86"},
    "d65380fd182744bea960a29fefffd9d3":{
      "scriptId":"u87"},
    "ec7d1d32d3484988babd024878d04fd9":{
      "scriptId":"u88"},
    "e2a2d7092a8949f3970eea5a853543b9":{
      "scriptId":"u89"},
    "3786fe04d9a04a289468b48dc3b2de8b":{
      "scriptId":"u90"},
    "ec870642343c44429d2c729f8337515e":{
      "scriptId":"u91"},
    "9815e1e4c6be4ba69a88f483d1959413":{
      "scriptId":"u92"},
    "2544e1ad47614693a7945e3f0db8ebfe":{
      "scriptId":"u93"},
    "8e53340cb974453e8da656add16983e6":{
      "scriptId":"u94"},
    "437deee6003b4db780d2584141433fec":{
      "scriptId":"u95"},
    "e7884f9eb3584ed89a7006d402ff39a5":{
      "scriptId":"u96"},
    "b9d114c525f4475187b51588406ba544":{
      "scriptId":"u97"},
    "1aad5bce083d4809ada57ab0e930ce15":{
      "scriptId":"u98"},
    "e31d38a5a9d54c3297565efea18c7cc7":{
      "scriptId":"u99"},
    "c14e89a89f0d4eb8ad6accb9e08a10ab":{
      "scriptId":"u100"},
    "195f92916ff74e329ca29f61a8c7e59a":{
      "scriptId":"u101"},
    "c9027f099c374076a9ef666a24caa6b9":{
      "scriptId":"u102"},
    "0398f51a786a4ffc9c5a0349b77ee25e":{
      "scriptId":"u103"},
    "ce6b9a27ef614daab9ab8f6ed544b0e7":{
      "scriptId":"u104"},
    "f392bd92b31b482f97d7689056c28f6a":{
      "scriptId":"u105"},
    "f730d017bf5a4941baf1d6aca08ae0f6":{
      "scriptId":"u106"},
    "7a6351b89fee482098dd6b2e4b95b14e":{
      "scriptId":"u107"},
    "57a3cc3b53fd43d49e9fa425772f0e0a":{
      "scriptId":"u108"},
    "8014e4b164144ead9f1bd45f912f58d7":{
      "scriptId":"u109"},
    "a9800bc08117481885fc6566f79f2bc7":{
      "scriptId":"u110"},
    "7f1963c85618425eafd528d6961f985e":{
      "scriptId":"u111"},
    "d4449eae1c6a49d1a348f5da179ef418":{
      "scriptId":"u112"},
    "34ee0ba8bab04cc59ac04d1edacb35c3":{
      "scriptId":"u113"},
    "f7983623e8ff4c93b50dd24a34f43556":{
      "scriptId":"u114"},
    "8a16cd78b96647659f7c20b4579c5a51":{
      "scriptId":"u115"},
    "3ddca6b7a37148d380474c1bc1f0012c":{
      "scriptId":"u116"},
    "ec8c306c5b704f10a8ca720624702a3e":{
      "scriptId":"u117"},
    "0ef9a41dd67546c1a8af1866c1e1bab3":{
      "scriptId":"u118"},
    "35bcdaf6e678403dbce1e285254a6146":{
      "scriptId":"u119"},
    "6e95cf4130de463fb47deaf2ac9d3aeb":{
      "scriptId":"u120"},
    "adde0f7075184c2dbcf9b434b607800d":{
      "scriptId":"u121"},
    "75264ec03cd844f78b56872c77239714":{
      "scriptId":"u122"},
    "e99b7a8a46b2453db07a5ed8005229a3":{
      "scriptId":"u123"},
    "6a4f8309ba4249d38003439536b381eb":{
      "scriptId":"u124"},
    "b27d40ae2d464d9ebd348b32439d3fd1":{
      "scriptId":"u125"},
    "cf5376fdc37f4dbd9ac44c26cf060bec":{
      "scriptId":"u126"}}});