$axure.loadCurrentPage({
  "url":"开通cdn服务.html",
  "generationDate":new Date(1405317795504.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2dfeb1799f3b43ca968984d0a93e285c",
    "type":"Axure:Page",
    "name":"开通CDN服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"41b002aa46494a5581f8e4592036a98e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":1000,
              "height":664},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4619825a28bf4f0280982a71b43cf92e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":1000,
                  "height":664},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cdn列表页/u0.png"}},
{
          "id":"84b018835f4e4802b9ef986d7ab8772a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "size":{
              "width":1000,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc734b56ba864b7987b129d573bf1406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":1000,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u2.png"}},
{
          "id":"0a8584d6467c42c8ac945c2dbe14f575",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dff9089c6ef45649a6ee18fe4acf78d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u4.png"}},
{
          "id":"ab86915d85384f8183d8558448e3f4fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":81,
              "y":25},
            "size":{
              "width":65,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efdf54d49772453fb2d0da63b8fc5675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":81,
                  "y":25},
                "size":{
                  "width":65,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c35f5f16e1034bc48387fc74f88792d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":180,
              "y":26},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7639de600bbf425fa15c37a3f9e63d49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":26},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a0e1ab852f14322a48f5e5676011045",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"94d06565f0a945acb90865ea94ac3dd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":251,
              "y":26},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a05e918b6304de5bc9f718585155798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":251,
                  "y":26},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0c91880210f4c85884b29882eaad083",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":295,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"276344a0cd274934b649cae7940d7b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":295,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"3e6e009d0ff2492fb604c04c03e35d50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":295,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c2856b2ba64044a50238307bf023ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":295,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"7994d4f6303645d29a52608d3a9e1454",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"bb6b378bd6ee43d0b7f79a2078d9cb37",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":324,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f075e448373c4ac7ba3b722573c92b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44d53e3934b8495baa4492f15baf5def",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"675c1d016a754a22ad6c2892081d6d82",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":407,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ea182c2a12495fa64cc90577261eb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":407,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0702599da3884715b06f20d944548078",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"cded2a3ede9e4995aaaff21bd8f78afb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":487,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413ae4ff7ab64cc899d74cb142ae9f82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":487,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"001c634a25ea4694be38e46e14f50b94",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"e0bc11d7790a4a2bbed948944ff5762c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":567,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7834602454864585a77ddfdbd7586d9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":567,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7996e0b6fa7e41f5a13f9035af8c34b9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":23},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理中心总览/u10_line.png"}},
{
          "id":"34d035725548440688cc892c60824b62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":647,
              "y":26},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5100db31b34fa281096f5688bb1af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":647,
                  "y":26},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"264ab4ee9da145b5ad3c34c8ef8d541a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":252,
              "y":64},
            "size":{
              "width":49,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"298c0c4ade824b538c32b28067cc2beb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":252,
                  "y":64},
                "size":{
                  "width":49,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u32.png"}},
{
          "id":"2e036ec16b084d10862f0c86f400a8db",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":765,
              "y":28},
            "size":{
              "width":139,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c46bbad89c46ea83bc9d4241b8eae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":765,
                  "y":28},
                "size":{
                  "width":139,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02b21955fa8247188086613311e2eb03",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":936,
              "y":27},
            "size":{
              "width":25,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6cfa26d48bc4af5aa621bdd54863d4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":936,
                  "y":27},
                "size":{
                  "width":25,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de79e3c866904a3089b7d9b1d6355937",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "location":{
              "x":381,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22186bf12a0a4a9fb619b63844fe6f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "location":{
                  "x":381,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u13.png"}},
{
          "id":"820463b1ca974f77b6aaa2ed435e4e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":381,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2355199d1adc427eb1b5ae73daddb0af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":381,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"cd86606caac547ebb6bef0affbdd87af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":913,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae0d4bef41841e7a14982f514ca6c8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":913,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"beb8d93d4e5e4d11906240d97aafc905",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":913,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59f906a03f424692a50e497e2f4a051e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":913,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"f6a7eedd7bc745e3aef1aaf978ad178c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":964,
              "y":32},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edfd390101e4479b9ae13cbed7bc770e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":964,
                  "y":32},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u42.png"}},
{
          "id":"7ea7ddc5bca74cc8a7a05a9e76e28d95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":964,
              "y":30},
            "size":{
              "width":6,
              "height":4},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e7c2109a3dd4c67be52eecb516a24b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":964,
                  "y":30},
                "size":{
                  "width":6,
                  "height":4},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u15.png"}},
{
          "id":"4aafe1187a834c79b75a9605cee7ff97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "location":{
              "x":903,
              "y":13},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CBFF},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f633945b35451cb3c3af660041034b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "location":{
                  "x":903,
                  "y":13},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CBFF},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理中心总览/u100.png"}},
{
          "id":"215f0eed2dfe4564a05d15f447a512d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":30,
              "y":91},
            "size":{
              "width":443,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c14d7395850a4be9b17c216bc5442ac9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":30,
                  "y":91},
                "size":{
                  "width":443,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e03accdb98ab43ffb61791c5b83b955b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":30,
              "y":144},
            "size":{
              "width":200,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532a909740cf4cdb95970cfe66aaea87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":30,
                  "y":144},
                "size":{
                  "width":200,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u73.png"}},
{
          "id":"a99e1106725f48768f2ba43cf605c72f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":245,
              "y":145},
            "size":{
              "width":200,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5994cd127cd442281fc739e1c75d99c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":245,
                  "y":145},
                "size":{
                  "width":200,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u75.png"}},
{
          "id":"2077e9e348f7465aa83b06e4a5f412cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":460,
              "y":145},
            "size":{
              "width":200,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8145fbb293a84af784c37d3aafae357c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":460,
                  "y":145},
                "size":{
                  "width":200,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u75.png"}},
{
          "id":"a804b9d3d1a049fca2ddd07b1f77d2ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":56,
              "y":126},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c4e63bb8ed24109bbb60e86b768d530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":126},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25524ad8ff5e4275bd08c1ff5ee47a6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":310,
              "y":125},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2c93f13c80e44bf8475275c5a352db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":125},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8aec58f0c56475e8301e44f00f57a91",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":524.5,
              "y":125},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63d8fcb828c047e3914bafd4ef3f3b4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":524.5,
                  "y":125},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bba7e6930fa5492b814ec47b946a1895",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":43,
              "y":176},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"788b9dcb5a0b46e390a32aa5def2cb02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":43,
                  "y":176},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f674a9d72ad4f7faa6cf8cfa9c41f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":114,
              "y":168},
            "size":{
              "width":80,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bacf5a74370d41ab85ef48568608c15b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":114,
                  "y":168},
                "size":{
                  "width":80,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u93.png"}},
{
          "id":"13f73587886d47f2b8ebe2c232eea16b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "location":{
              "x":114,
              "y":168},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF199ED7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ba13a69758945598bb3fa5cfc82679b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "location":{
                  "x":114,
                  "y":168},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ebs磁盘/u69.png"}},
{
          "id":"44f5643de723417daca50afb17dbb3c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":57,
              "y":217},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"311e70ce228e44edb2b097fca8081edb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":57,
                  "y":217},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a1570caeb444cb69fb1b17c8e32e08e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":247},
            "size":{
              "width":599,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/创建实例（无购物车）/u175_line.png"}},
{
          "id":"9d5a552c79d54bbfbe81d24c3aec4b14",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":113,
              "y":272},
            "size":{
              "width":171,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4c5fe61695d4f9682a54945f6870bc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":113,
                  "y":272},
                "size":{
                  "width":171,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"112b14a04756425b8c6a077b43410e13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":114,
              "y":310},
            "size":{
              "width":170,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69342635c4964ae3828bdde81af84efd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":114,
                  "y":310},
                "size":{
                  "width":170,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建实例（无购物车）/u178.png"}},
{
          "id":"9cbf84b9774f49f8bfa234b8fdd0ad7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontWeight":"400",
            "location":{
              "x":303,
              "y":272},
            "size":{
              "width":189,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b3d65f447ca4198b7fde0c96d845472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontWeight":"400",
                "location":{
                  "x":303,
                  "y":272},
                "size":{
                  "width":189,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaa95e2f83b9475c872f9fce00d93e87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF7F7F7},
            "location":{
              "x":234,
              "y":168},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29954e2671a74661906d381c4acddf5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7},
                "location":{
                  "x":234,
                  "y":168},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/s3列表/u88.png"}},
{
          "id":"1fed81720dea47269972408baf4a349e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'SimSun', 'SimSun'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":114,
              "y":217},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3390a0167f5d4ccab648cc4a51de0dfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'SimSun', 'SimSun'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":114,
                  "y":217},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "41b002aa46494a5581f8e4592036a98e":{
      "scriptId":"u0"},
    "4619825a28bf4f0280982a71b43cf92e":{
      "scriptId":"u1"},
    "84b018835f4e4802b9ef986d7ab8772a":{
      "scriptId":"u2"},
    "dc734b56ba864b7987b129d573bf1406":{
      "scriptId":"u3"},
    "0a8584d6467c42c8ac945c2dbe14f575":{
      "scriptId":"u4"},
    "6dff9089c6ef45649a6ee18fe4acf78d":{
      "scriptId":"u5"},
    "ab86915d85384f8183d8558448e3f4fb":{
      "scriptId":"u6"},
    "efdf54d49772453fb2d0da63b8fc5675":{
      "scriptId":"u7"},
    "c35f5f16e1034bc48387fc74f88792d1":{
      "scriptId":"u8"},
    "7639de600bbf425fa15c37a3f9e63d49":{
      "scriptId":"u9"},
    "4a0e1ab852f14322a48f5e5676011045":{
      "scriptId":"u10"},
    "94d06565f0a945acb90865ea94ac3dd8":{
      "scriptId":"u11"},
    "5a05e918b6304de5bc9f718585155798":{
      "scriptId":"u12"},
    "b0c91880210f4c85884b29882eaad083":{
      "scriptId":"u13"},
    "276344a0cd274934b649cae7940d7b85":{
      "scriptId":"u14"},
    "3e6e009d0ff2492fb604c04c03e35d50":{
      "scriptId":"u15"},
    "76c2856b2ba64044a50238307bf023ad":{
      "scriptId":"u16"},
    "7994d4f6303645d29a52608d3a9e1454":{
      "scriptId":"u17"},
    "bb6b378bd6ee43d0b7f79a2078d9cb37":{
      "scriptId":"u18"},
    "f075e448373c4ac7ba3b722573c92b08":{
      "scriptId":"u19"},
    "44d53e3934b8495baa4492f15baf5def":{
      "scriptId":"u20"},
    "675c1d016a754a22ad6c2892081d6d82":{
      "scriptId":"u21"},
    "e6ea182c2a12495fa64cc90577261eb1":{
      "scriptId":"u22"},
    "0702599da3884715b06f20d944548078":{
      "scriptId":"u23"},
    "cded2a3ede9e4995aaaff21bd8f78afb":{
      "scriptId":"u24"},
    "413ae4ff7ab64cc899d74cb142ae9f82":{
      "scriptId":"u25"},
    "001c634a25ea4694be38e46e14f50b94":{
      "scriptId":"u26"},
    "e0bc11d7790a4a2bbed948944ff5762c":{
      "scriptId":"u27"},
    "7834602454864585a77ddfdbd7586d9c":{
      "scriptId":"u28"},
    "7996e0b6fa7e41f5a13f9035af8c34b9":{
      "scriptId":"u29"},
    "34d035725548440688cc892c60824b62":{
      "scriptId":"u30"},
    "9f5100db31b34fa281096f5688bb1af6":{
      "scriptId":"u31"},
    "264ab4ee9da145b5ad3c34c8ef8d541a":{
      "scriptId":"u32"},
    "298c0c4ade824b538c32b28067cc2beb":{
      "scriptId":"u33"},
    "2e036ec16b084d10862f0c86f400a8db":{
      "scriptId":"u34"},
    "87c46bbad89c46ea83bc9d4241b8eae8":{
      "scriptId":"u35"},
    "02b21955fa8247188086613311e2eb03":{
      "scriptId":"u36"},
    "a6cfa26d48bc4af5aa621bdd54863d4c":{
      "scriptId":"u37"},
    "de79e3c866904a3089b7d9b1d6355937":{
      "scriptId":"u38"},
    "22186bf12a0a4a9fb619b63844fe6f70":{
      "scriptId":"u39"},
    "820463b1ca974f77b6aaa2ed435e4e8a":{
      "scriptId":"u40"},
    "2355199d1adc427eb1b5ae73daddb0af":{
      "scriptId":"u41"},
    "cd86606caac547ebb6bef0affbdd87af":{
      "scriptId":"u42"},
    "9ae0d4bef41841e7a14982f514ca6c8a":{
      "scriptId":"u43"},
    "beb8d93d4e5e4d11906240d97aafc905":{
      "scriptId":"u44"},
    "59f906a03f424692a50e497e2f4a051e":{
      "scriptId":"u45"},
    "f6a7eedd7bc745e3aef1aaf978ad178c":{
      "scriptId":"u46"},
    "edfd390101e4479b9ae13cbed7bc770e":{
      "scriptId":"u47"},
    "7ea7ddc5bca74cc8a7a05a9e76e28d95":{
      "scriptId":"u48"},
    "9e7c2109a3dd4c67be52eecb516a24b9":{
      "scriptId":"u49"},
    "4aafe1187a834c79b75a9605cee7ff97":{
      "scriptId":"u50"},
    "73f633945b35451cb3c3af660041034b":{
      "scriptId":"u51"},
    "215f0eed2dfe4564a05d15f447a512d7":{
      "scriptId":"u52"},
    "c14d7395850a4be9b17c216bc5442ac9":{
      "scriptId":"u53"},
    "e03accdb98ab43ffb61791c5b83b955b":{
      "scriptId":"u54"},
    "532a909740cf4cdb95970cfe66aaea87":{
      "scriptId":"u55"},
    "a99e1106725f48768f2ba43cf605c72f":{
      "scriptId":"u56"},
    "b5994cd127cd442281fc739e1c75d99c":{
      "scriptId":"u57"},
    "2077e9e348f7465aa83b06e4a5f412cd":{
      "scriptId":"u58"},
    "8145fbb293a84af784c37d3aafae357c":{
      "scriptId":"u59"},
    "a804b9d3d1a049fca2ddd07b1f77d2ad":{
      "scriptId":"u60"},
    "4c4e63bb8ed24109bbb60e86b768d530":{
      "scriptId":"u61"},
    "25524ad8ff5e4275bd08c1ff5ee47a6b":{
      "scriptId":"u62"},
    "f2c93f13c80e44bf8475275c5a352db8":{
      "scriptId":"u63"},
    "c8aec58f0c56475e8301e44f00f57a91":{
      "scriptId":"u64"},
    "63d8fcb828c047e3914bafd4ef3f3b4f":{
      "scriptId":"u65"},
    "bba7e6930fa5492b814ec47b946a1895":{
      "scriptId":"u66"},
    "788b9dcb5a0b46e390a32aa5def2cb02":{
      "scriptId":"u67"},
    "1f674a9d72ad4f7faa6cf8cfa9c41f0f":{
      "scriptId":"u68"},
    "bacf5a74370d41ab85ef48568608c15b":{
      "scriptId":"u69"},
    "13f73587886d47f2b8ebe2c232eea16b":{
      "scriptId":"u70"},
    "7ba13a69758945598bb3fa5cfc82679b":{
      "scriptId":"u71"},
    "44f5643de723417daca50afb17dbb3c5":{
      "scriptId":"u72"},
    "311e70ce228e44edb2b097fca8081edb":{
      "scriptId":"u73"},
    "1a1570caeb444cb69fb1b17c8e32e08e":{
      "scriptId":"u74"},
    "9d5a552c79d54bbfbe81d24c3aec4b14":{
      "scriptId":"u75"},
    "e4c5fe61695d4f9682a54945f6870bc4":{
      "scriptId":"u76"},
    "112b14a04756425b8c6a077b43410e13":{
      "scriptId":"u77"},
    "69342635c4964ae3828bdde81af84efd":{
      "scriptId":"u78"},
    "9cbf84b9774f49f8bfa234b8fdd0ad7f":{
      "scriptId":"u79"},
    "0b3d65f447ca4198b7fde0c96d845472":{
      "scriptId":"u80"},
    "eaa95e2f83b9475c872f9fce00d93e87":{
      "scriptId":"u81"},
    "29954e2671a74661906d381c4acddf5e":{
      "scriptId":"u82"},
    "1fed81720dea47269972408baf4a349e":{
      "scriptId":"u83"},
    "3390a0167f5d4ccab648cc4a51de0dfa":{
      "scriptId":"u84"}}});