$axure.loadCurrentPage({
  "url":"注册页.html",
  "generationDate":new Date(1405317737347.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0d7ffca4948d440ca9de07c49482271c",
    "type":"Axure:Page",
    "name":"注册页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"28e3947081c44824889a8ef97d8b7f4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1000,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35a35686f43e42438d4a2a278a6d5d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1000,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u0.png"}},
{
          "id":"18554de10c4c4ba0aa8b9df8b5af782d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"24px",
            "fontWeight":"200",
            "fontStyle":"normal",
            "location":{
              "x":45,
              "y":25},
            "size":{
              "width":73,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f5228de428f46518e620e924299081e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"24px",
                "fontWeight":"200",
                "fontStyle":"normal",
                "location":{
                  "x":45,
                  "y":25},
                "size":{
                  "width":73,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d1513f713b94fa38aacdc0998857d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":206,
              "y":29},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32e37610c3624251beb27611caff2e96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":206,
                  "y":29},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25dfc1dcc8384a128b03631ea33efdcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":402,
              "y":29},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1187bcbd9dd2408cacd0a4f188effb20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":402,
                  "y":29},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e343fc19e0c47e2a1aa37366e7d8b87",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":305,
              "y":29},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd4af32449c49cf87449bfaf44b7013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":305,
                  "y":29},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a218b0b903664efe84764a0d2f87dd92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":512,
              "y":29},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a0e1b154afb45688662df5d80f72628",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":512,
                  "y":29},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfd671f36ef54dfca08d8dc0f835ab2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":944,
              "y":26},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5337d5fba6204e2f88d4fbce6c7c85b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":944,
                  "y":26},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a3e5a01fd1b4ae496ca4381b8412257",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":860,
              "y":26},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27ad3f1e169490c9e96059c02e19b29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":860,
                  "y":26},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"315268b3734345e3a972c9e3929829ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":827,
              "y":21},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a6070b8df904e5dae8cbcd4527432ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":827,
                  "y":21},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u25.png"}},
{
          "id":"691f4ba51b354b22bf0d270b57717523",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":20},
            "size":{
              "width":29,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ac6a0972b7407dad193ba1c2d0d9b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":20},
                "size":{
                  "width":29,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u27.png"}},
{
          "id":"16608055a2c141378300419b214b9a40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":835,
              "y":26},
            "size":{
              "width":11,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12c1bee4aca146cf9890afd8dc883876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":835,
                  "y":26},
                "size":{
                  "width":11,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u29.png"}},
{
          "id":"e840df715fde4d55857895ee9b32a81f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f15d6cc482064a0093e037224487122b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"d99db3ff589040abbf749818233e0fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":147,
              "y":29},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c26b0c7510fb4f7b97ba57dad77ea1de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":147,
                  "y":29},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e1992127ae34e808704c30e41fe520c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7067e54e875f4baa9b373708faf05f93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"9793707a35334152a9487a0a4ec2fa0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c7256e9b23a40d6b20e07a8efd811e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"815f4e6879c34e688c8b7b498c1dd696",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":30},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee02ccc88b44c60bc323cda5c0a1d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":30},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页样式一/u31.png"}},
{
          "id":"7cb91eb7b66242f7bc20448cc439be59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":832,
              "y":64},
            "size":{
              "width":62,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b14587b62da2477ca40a299283a442a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":832,
                  "y":64},
                "size":{
                  "width":62,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u32.png"}},
{
          "id":"01777c0f18d04df49a8b815d80607071",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":1000,
              "height":571}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d032bfd4f3bf4b3b80a6889f81f44286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":1000,
                  "height":571}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u34.png"}},
{
          "id":"ba4a6f16eaec4b43995d8c7ad940c1dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":118,
              "y":115},
            "size":{
              "width":132,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74b8676a32c34f429f053895bba6bef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":118,
                  "y":115},
                "size":{
                  "width":132,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u36.png"}},
{
          "id":"248f67464a454c06baedf7bb7c490846",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":264,
              "y":97},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21da4c712a654f409e0361be1fa63fff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":264,
                  "y":97},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u38.png"}},
{
          "id":"d34985f3b767458780266c3adfd57544",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":317,
              "y":115},
            "size":{
              "width":154,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"625f7904806b4fabb9510174a9dcb137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":317,
                  "y":115},
                "size":{
                  "width":154,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u40.png"}},
{
          "id":"8852bbf49a704aac91252df810415d63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":97},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"055019105ab34b92a8e90a32af97ed20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":97},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u42.png"}},
{
          "id":"96d008b8e6984b6aa6e73bac0edad09b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":97},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef9f6b792014838b66356800708720d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":97},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u42.png"}},
{
          "id":"54923b875dec4b9e9de80337b016c1a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":758,
              "y":115},
            "size":{
              "width":132,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f2dc0c5b5d642abb6fe94b02d6d0d13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":758,
                  "y":115},
                "size":{
                  "width":132,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u36.png"}},
{
          "id":"8d9b2d3d83d64fa09cc39383a93bf963",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":537,
              "y":115},
            "size":{
              "width":154,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db3ae195a28a47e8a8226e4e4010f390",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":537,
                  "y":115},
                "size":{
                  "width":154,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u40.png"}},
{
          "id":"e960e9e1c249454d9220ed633cc73cb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":242,
              "y":146},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50f15368d1a64fb1a682e4e4a27cba7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":242,
                  "y":146},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71d793479f654029a911a22b88379044",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":459,
              "y":147},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5934ed47303d4616b7f09bea94f7021b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":459,
                  "y":147},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6ef05e7c3504ecf8c8feb4fb3851b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":693,
              "y":147},
            "size":{
              "width":57,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"511360d16ed4433da37a3b1d6e546f11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":693,
                  "y":147},
                "size":{
                  "width":57,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"557d6c3f5ab7466a96edd812b6635ffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":191},
            "size":{
              "width":722,
              "height":389},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"342cf243800c4353bb5db086ac540826",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":191},
                "size":{
                  "width":722,
                  "height":389},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u56.png"}},
{
          "id":"09701cbe12eb482fac4926f414741887",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":409},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f99ff9dafaa34f13bef0a409f118ab05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":409},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u58.png"}},
{
          "id":"389b13f478224fc1950c5959da146c42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":413},
            "size":{
              "width":13,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eadf64db83e469c8e5446033f8434b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":413},
                "size":{
                  "width":13,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面隐藏/u50.png"}},
{
          "id":"50aab44da20a40f899198649692934d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":252},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b456cae85112400b88852b4d378fdc84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":252},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u58.png"}},
{
          "id":"457967517d674946851a76c0780a3e8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":260},
            "size":{
              "width":21,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baabfb89577044c280b1d40b69cf2e69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":260},
                "size":{
                  "width":21,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u64.png"}},
{
          "id":"82e653808924458ab733367cae826a9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":190,
              "y":285},
            "size":{
              "width":29,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15b8a726f77244dcbc96faafb4fb0821",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":190,
                  "y":285},
                "size":{
                  "width":29,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9fec371d9af440d976b9ad72f2bbea8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":206},
            "size":{
              "width":10,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册页/u68_line.png"}},
{
          "id":"32a152f69e4d4aac847c26e42bc248c9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":319},
            "size":{
              "width":10,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册页/u68_line.png"}},
{
          "id":"a1833ba4caa3434faf56982945917c2f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":370},
            "size":{
              "width":590,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册页/u70_line.png"}},
{
          "id":"8cf7d07b4b824ce392680f3aaad800b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":289,
              "y":232},
            "size":{
              "width":81,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d32b6f3c4384e3c9a231893a131e387",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":289,
                  "y":232},
                "size":{
                  "width":81,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7e29ff153ce4a3c832e84746d25792c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":225},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bd09c91d2434244aa5799cc7d9b8f80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":225},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u73.png"}},
{
          "id":"c610f22355ce49668377d5d42650e0da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":385,
              "y":234},
            "size":{
              "width":133,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ffe2ab1e2e54521901f9dfd9e04aa3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":385,
                  "y":234},
                "size":{
                  "width":133,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62b6930fceb242a9aae0d2c9edc83388",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":289,
              "y":279},
            "size":{
              "width":81,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3b262e23c7747c1be42e0ff660713e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":289,
                  "y":279},
                "size":{
                  "width":81,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bff7ebe9391441cc8ea2dfaa0a93b006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":270},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82981208866470f8f8448be8a242573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":270},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u73.png"}},
{
          "id":"d5bfd7645d0a49ddad7239c68ac60d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":261,
              "y":323},
            "size":{
              "width":109,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca7b2824c6640998921c650a9e0496a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":261,
                  "y":323},
                "size":{
                  "width":109,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b84211105c5b4b278bc7ac5fa9b8d8f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":314},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"931ca457b444440da0ad6c5a77c2ed7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":314},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u73.png"}},
{
          "id":"11a78eba77e244159034b7929c60d17a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":679,
              "y":274},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89077093db2e405f9f2dff186f504ce5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":679,
                  "y":274},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u85.png"}},
{
          "id":"64443bb7ff30467a9f62e92b62da3091",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":721,
              "y":274},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0864f8102816413c8bc0bd3223dae9a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":721,
                  "y":274},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u85.png"}},
{
          "id":"caffa2001f8e48938588a6f6502713fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":763,
              "y":274},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21501d56c76949acae6c0b39a4f63d11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":763,
                  "y":274},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u89.png"}},
{
          "id":"c089dd8650a84e828205c86c0643b68b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":388},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册页/u91_line.png"}},
{
          "id":"50d33c53c4c74397bfd5869d7dc04635",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":190,
              "y":447},
            "size":{
              "width":29,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b7bc35e5f1426eb630aba310a4d32e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":190,
                  "y":447},
                "size":{
                  "width":29,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0540759024de4212976af03f80532349",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":289,
              "y":407},
            "size":{
              "width":81,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4c27504a46438399ba814f6d5ee49e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":289,
                  "y":407},
                "size":{
                  "width":81,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f70ed0c3a324b10b82d51b78321ae3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":400},
            "size":{
              "width":300,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ad18a2f02e2413da363a97d73cea319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":400},
                "size":{
                  "width":300,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u73.png"}},
{
          "id":"f3caee21a5c24d4e8d6c6a6994efa485",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":385,
              "y":409},
            "size":{
              "width":181,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75cda416b7f8400caf971b884553da92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":385,
                  "y":409},
                "size":{
                  "width":181,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"072f603af8e7406d932b0194e14a2b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"10px",
            "fontWeight":"200",
            "location":{
              "x":680,
              "y":402},
            "size":{
              "width":106,
              "height":25},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a687cc9542b45f790f125d5b6412556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"10px",
                "fontWeight":"200",
                "location":{
                  "x":680,
                  "y":402},
                "size":{
                  "width":106,
                  "height":25},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u100.png"}},
{
          "id":"a265acf9706b4148a0e9dae1f393577f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":274,
              "y":451},
            "size":{
              "width":95,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf197fe9dec4cceb9a3749d88ef099b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":274,
                  "y":451},
                "size":{
                  "width":95,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78815d58498549ba88467d68b292cf4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":444},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e945508c53aa49019908c396d709a52b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":444},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u104.png"}},
{
          "id":"134aeef3d2374a848f7b43bdd22d8ca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":391,
              "y":453},
            "size":{
              "width":44,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2eca70e2ca14932b46e129c385d36da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":391,
                  "y":453},
                "size":{
                  "width":44,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b1481bf9b0f48ae87aac98339f84c6b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":480},
            "size":{
              "width":10,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册页/u91_line.png"}},
{
          "id":"ec10e08488b74d6285cb43f1dc62db2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":370,
              "y":495},
            "size":{
              "width":130,
              "height":40},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ee3a3a264d4925a5668336c5087ee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":370,
                  "y":495},
                "size":{
                  "width":130,
                  "height":40},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册页/u109.png"}},
{
          "id":"f95fb552ae4d4e4bae21a06c6571df46",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF199ED7,
              "opacity":1},
            "location":{
              "x":519,
              "y":509},
            "size":{
              "width":133,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b9555da140f46bd8023b9ba4a4d5eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF199ED7,
                  "opacity":1},
                "location":{
                  "x":519,
                  "y":509},
                "size":{
                  "width":133,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "28e3947081c44824889a8ef97d8b7f4c":{
      "scriptId":"u0"},
    "35a35686f43e42438d4a2a278a6d5d65":{
      "scriptId":"u1"},
    "18554de10c4c4ba0aa8b9df8b5af782d":{
      "scriptId":"u2"},
    "7f5228de428f46518e620e924299081e":{
      "scriptId":"u3"},
    "8d1513f713b94fa38aacdc0998857d6d":{
      "scriptId":"u4"},
    "32e37610c3624251beb27611caff2e96":{
      "scriptId":"u5"},
    "25dfc1dcc8384a128b03631ea33efdcc":{
      "scriptId":"u6"},
    "1187bcbd9dd2408cacd0a4f188effb20":{
      "scriptId":"u7"},
    "7e343fc19e0c47e2a1aa37366e7d8b87":{
      "scriptId":"u8"},
    "2bd4af32449c49cf87449bfaf44b7013":{
      "scriptId":"u9"},
    "a218b0b903664efe84764a0d2f87dd92":{
      "scriptId":"u10"},
    "1a0e1b154afb45688662df5d80f72628":{
      "scriptId":"u11"},
    "cfd671f36ef54dfca08d8dc0f835ab2d":{
      "scriptId":"u12"},
    "5337d5fba6204e2f88d4fbce6c7c85b3":{
      "scriptId":"u13"},
    "4a3e5a01fd1b4ae496ca4381b8412257":{
      "scriptId":"u14"},
    "f27ad3f1e169490c9e96059c02e19b29":{
      "scriptId":"u15"},
    "315268b3734345e3a972c9e3929829ee":{
      "scriptId":"u16"},
    "7a6070b8df904e5dae8cbcd4527432ee":{
      "scriptId":"u17"},
    "691f4ba51b354b22bf0d270b57717523":{
      "scriptId":"u18"},
    "24ac6a0972b7407dad193ba1c2d0d9b6":{
      "scriptId":"u19"},
    "16608055a2c141378300419b214b9a40":{
      "scriptId":"u20"},
    "12c1bee4aca146cf9890afd8dc883876":{
      "scriptId":"u21"},
    "e840df715fde4d55857895ee9b32a81f":{
      "scriptId":"u22"},
    "f15d6cc482064a0093e037224487122b":{
      "scriptId":"u23"},
    "d99db3ff589040abbf749818233e0fad":{
      "scriptId":"u24"},
    "c26b0c7510fb4f7b97ba57dad77ea1de":{
      "scriptId":"u25"},
    "9e1992127ae34e808704c30e41fe520c":{
      "scriptId":"u26"},
    "7067e54e875f4baa9b373708faf05f93":{
      "scriptId":"u27"},
    "9793707a35334152a9487a0a4ec2fa0c":{
      "scriptId":"u28"},
    "8c7256e9b23a40d6b20e07a8efd811e3":{
      "scriptId":"u29"},
    "815f4e6879c34e688c8b7b498c1dd696":{
      "scriptId":"u30"},
    "0ee02ccc88b44c60bc323cda5c0a1d90":{
      "scriptId":"u31"},
    "7cb91eb7b66242f7bc20448cc439be59":{
      "scriptId":"u32"},
    "b14587b62da2477ca40a299283a442a7":{
      "scriptId":"u33"},
    "01777c0f18d04df49a8b815d80607071":{
      "scriptId":"u34"},
    "d032bfd4f3bf4b3b80a6889f81f44286":{
      "scriptId":"u35"},
    "ba4a6f16eaec4b43995d8c7ad940c1dc":{
      "scriptId":"u36"},
    "74b8676a32c34f429f053895bba6bef3":{
      "scriptId":"u37"},
    "248f67464a454c06baedf7bb7c490846":{
      "scriptId":"u38"},
    "21da4c712a654f409e0361be1fa63fff":{
      "scriptId":"u39"},
    "d34985f3b767458780266c3adfd57544":{
      "scriptId":"u40"},
    "625f7904806b4fabb9510174a9dcb137":{
      "scriptId":"u41"},
    "8852bbf49a704aac91252df810415d63":{
      "scriptId":"u42"},
    "055019105ab34b92a8e90a32af97ed20":{
      "scriptId":"u43"},
    "96d008b8e6984b6aa6e73bac0edad09b":{
      "scriptId":"u44"},
    "2ef9f6b792014838b66356800708720d":{
      "scriptId":"u45"},
    "54923b875dec4b9e9de80337b016c1a2":{
      "scriptId":"u46"},
    "7f2dc0c5b5d642abb6fe94b02d6d0d13":{
      "scriptId":"u47"},
    "8d9b2d3d83d64fa09cc39383a93bf963":{
      "scriptId":"u48"},
    "db3ae195a28a47e8a8226e4e4010f390":{
      "scriptId":"u49"},
    "e960e9e1c249454d9220ed633cc73cb8":{
      "scriptId":"u50"},
    "50f15368d1a64fb1a682e4e4a27cba7b":{
      "scriptId":"u51"},
    "71d793479f654029a911a22b88379044":{
      "scriptId":"u52"},
    "5934ed47303d4616b7f09bea94f7021b":{
      "scriptId":"u53"},
    "d6ef05e7c3504ecf8c8feb4fb3851b32":{
      "scriptId":"u54"},
    "511360d16ed4433da37a3b1d6e546f11":{
      "scriptId":"u55"},
    "557d6c3f5ab7466a96edd812b6635ffc":{
      "scriptId":"u56"},
    "342cf243800c4353bb5db086ac540826":{
      "scriptId":"u57"},
    "09701cbe12eb482fac4926f414741887":{
      "scriptId":"u58"},
    "f99ff9dafaa34f13bef0a409f118ab05":{
      "scriptId":"u59"},
    "389b13f478224fc1950c5959da146c42":{
      "scriptId":"u60"},
    "8eadf64db83e469c8e5446033f8434b0":{
      "scriptId":"u61"},
    "50aab44da20a40f899198649692934d1":{
      "scriptId":"u62"},
    "b456cae85112400b88852b4d378fdc84":{
      "scriptId":"u63"},
    "457967517d674946851a76c0780a3e8f":{
      "scriptId":"u64"},
    "baabfb89577044c280b1d40b69cf2e69":{
      "scriptId":"u65"},
    "82e653808924458ab733367cae826a9a":{
      "scriptId":"u66"},
    "15b8a726f77244dcbc96faafb4fb0821":{
      "scriptId":"u67"},
    "f9fec371d9af440d976b9ad72f2bbea8":{
      "scriptId":"u68"},
    "32a152f69e4d4aac847c26e42bc248c9":{
      "scriptId":"u69"},
    "a1833ba4caa3434faf56982945917c2f":{
      "scriptId":"u70"},
    "8cf7d07b4b824ce392680f3aaad800b2":{
      "scriptId":"u71"},
    "2d32b6f3c4384e3c9a231893a131e387":{
      "scriptId":"u72"},
    "e7e29ff153ce4a3c832e84746d25792c":{
      "scriptId":"u73"},
    "9bd09c91d2434244aa5799cc7d9b8f80":{
      "scriptId":"u74"},
    "c610f22355ce49668377d5d42650e0da":{
      "scriptId":"u75"},
    "1ffe2ab1e2e54521901f9dfd9e04aa3d":{
      "scriptId":"u76"},
    "62b6930fceb242a9aae0d2c9edc83388":{
      "scriptId":"u77"},
    "a3b262e23c7747c1be42e0ff660713e9":{
      "scriptId":"u78"},
    "bff7ebe9391441cc8ea2dfaa0a93b006":{
      "scriptId":"u79"},
    "f82981208866470f8f8448be8a242573":{
      "scriptId":"u80"},
    "d5bfd7645d0a49ddad7239c68ac60d6d":{
      "scriptId":"u81"},
    "bca7b2824c6640998921c650a9e0496a":{
      "scriptId":"u82"},
    "b84211105c5b4b278bc7ac5fa9b8d8f3":{
      "scriptId":"u83"},
    "931ca457b444440da0ad6c5a77c2ed7b":{
      "scriptId":"u84"},
    "11a78eba77e244159034b7929c60d17a":{
      "scriptId":"u85"},
    "89077093db2e405f9f2dff186f504ce5":{
      "scriptId":"u86"},
    "64443bb7ff30467a9f62e92b62da3091":{
      "scriptId":"u87"},
    "0864f8102816413c8bc0bd3223dae9a4":{
      "scriptId":"u88"},
    "caffa2001f8e48938588a6f6502713fa":{
      "scriptId":"u89"},
    "21501d56c76949acae6c0b39a4f63d11":{
      "scriptId":"u90"},
    "c089dd8650a84e828205c86c0643b68b":{
      "scriptId":"u91"},
    "50d33c53c4c74397bfd5869d7dc04635":{
      "scriptId":"u92"},
    "a8b7bc35e5f1426eb630aba310a4d32e":{
      "scriptId":"u93"},
    "0540759024de4212976af03f80532349":{
      "scriptId":"u94"},
    "ad4c27504a46438399ba814f6d5ee49e":{
      "scriptId":"u95"},
    "9f70ed0c3a324b10b82d51b78321ae3b":{
      "scriptId":"u96"},
    "5ad18a2f02e2413da363a97d73cea319":{
      "scriptId":"u97"},
    "f3caee21a5c24d4e8d6c6a6994efa485":{
      "scriptId":"u98"},
    "75cda416b7f8400caf971b884553da92":{
      "scriptId":"u99"},
    "072f603af8e7406d932b0194e14a2b7f":{
      "scriptId":"u100"},
    "1a687cc9542b45f790f125d5b6412556":{
      "scriptId":"u101"},
    "a265acf9706b4148a0e9dae1f393577f":{
      "scriptId":"u102"},
    "cbf197fe9dec4cceb9a3749d88ef099b":{
      "scriptId":"u103"},
    "78815d58498549ba88467d68b292cf4d":{
      "scriptId":"u104"},
    "e945508c53aa49019908c396d709a52b":{
      "scriptId":"u105"},
    "134aeef3d2374a848f7b43bdd22d8ca0":{
      "scriptId":"u106"},
    "c2eca70e2ca14932b46e129c385d36da":{
      "scriptId":"u107"},
    "5b1481bf9b0f48ae87aac98339f84c6b":{
      "scriptId":"u108"},
    "ec10e08488b74d6285cb43f1dc62db2c":{
      "scriptId":"u109"},
    "24ee3a3a264d4925a5668336c5087ee1":{
      "scriptId":"u110"},
    "f95fb552ae4d4e4bae21a06c6571df46":{
      "scriptId":"u111"},
    "7b9555da140f46bd8023b9ba4a4d5eb3":{
      "scriptId":"u112"}}});